// This file was generated by ODB, object-relational mapping (ORM)
// compiler for C++.
//

#include <odb/pre.hxx>

#include "ComplianceData-odb.hxx"

#include <cassert>
#include <cstring>  // std::memcpy

#include <odb/schema-catalog-impl.hxx>

#include <odb/mysql/traits.hxx>
#include <odb/mysql/database.hxx>
#include <odb/mysql/transaction.hxx>
#include <odb/mysql/connection.hxx>
#include <odb/mysql/statement.hxx>
#include <odb/mysql/statement-cache.hxx>
#include <odb/mysql/simple-object-statements.hxx>
#include <odb/mysql/container-statements.hxx>
#include <odb/mysql/exceptions.hxx>
#include <odb/mysql/simple-object-result.hxx>
#include <odb/mysql/enum.hxx>

namespace odb
{
  // ComplianceData
  //

  struct access::object_traits_impl< ::TR::Core::ComplianceData, id_mysql >::extra_statement_cache_type
  {
    extra_statement_cache_type (
      mysql::connection&,
      image_type&,
      id_image_type&,
      mysql::binding&,
      mysql::binding&)
    {
    }
  };

  access::object_traits_impl< ::TR::Core::ComplianceData, id_mysql >::id_type
  access::object_traits_impl< ::TR::Core::ComplianceData, id_mysql >::
  id (const image_type& i)
  {
    mysql::database* db (0);
    ODB_POTENTIALLY_UNUSED (db);

    id_type id;
    {
      mysql::value_traits<
          ::TR::Core::Key,
          mysql::id_long >::set_value (
        id,
        i.m_key_value,
        i.m_key_null);
    }

    return id;
  }

  bool access::object_traits_impl< ::TR::Core::ComplianceData, id_mysql >::
  grow (image_type& i,
        my_bool* t)
  {
    ODB_POTENTIALLY_UNUSED (i);
    ODB_POTENTIALLY_UNUSED (t);

    bool grew (false);

    // m_key
    //
    t[0UL] = 0;

    // m_name
    //
    if (t[1UL])
    {
      i.m_name_value.capacity (i.m_name_size);
      grew = true;
    }

    // m_input_uuid
    //
    if (composite_value_traits< ::TR::Core::ReportTypeUUID, id_mysql >::grow (
          i.m_input_uuid_value, t + 2UL))
      grew = true;

    // m_output_uuid
    //
    if (composite_value_traits< ::TR::Core::ReportTypeUUID, id_mysql >::grow (
          i.m_output_uuid_value, t + 3UL))
      grew = true;

    return grew;
  }

  void access::object_traits_impl< ::TR::Core::ComplianceData, id_mysql >::
  bind (MYSQL_BIND* b,
        image_type& i,
        mysql::statement_kind sk)
  {
    ODB_POTENTIALLY_UNUSED (sk);

    using namespace mysql;

    std::size_t n (0);

    // m_key
    //
    if (sk != statement_update)
    {
      b[n].buffer_type = MYSQL_TYPE_LONG;
      b[n].is_unsigned = 0;
      b[n].buffer = &i.m_key_value;
      b[n].is_null = &i.m_key_null;
      n++;
    }

    // m_name
    //
    b[n].buffer_type = MYSQL_TYPE_STRING;
    b[n].buffer = i.m_name_value.data ();
    b[n].buffer_length = static_cast<unsigned long> (
      i.m_name_value.capacity ());
    b[n].length = &i.m_name_size;
    b[n].is_null = &i.m_name_null;
    n++;

    // m_input_uuid
    //
    composite_value_traits< ::TR::Core::ReportTypeUUID, id_mysql >::bind (
      b + n, i.m_input_uuid_value, sk);
    n += 1UL;

    // m_output_uuid
    //
    composite_value_traits< ::TR::Core::ReportTypeUUID, id_mysql >::bind (
      b + n, i.m_output_uuid_value, sk);
    n += 1UL;
  }

  void access::object_traits_impl< ::TR::Core::ComplianceData, id_mysql >::
  bind (MYSQL_BIND* b, id_image_type& i)
  {
    std::size_t n (0);
    b[n].buffer_type = MYSQL_TYPE_LONG;
    b[n].is_unsigned = 0;
    b[n].buffer = &i.id_value;
    b[n].is_null = &i.id_null;
  }

  bool access::object_traits_impl< ::TR::Core::ComplianceData, id_mysql >::
  init (image_type& i,
        const object_type& o,
        mysql::statement_kind sk)
  {
    ODB_POTENTIALLY_UNUSED (i);
    ODB_POTENTIALLY_UNUSED (o);
    ODB_POTENTIALLY_UNUSED (sk);

    using namespace mysql;

    bool grew (false);

    // m_key
    //
    if (sk == statement_insert)
    {
      ::TR::Core::Key const& v =
        o.m_key;

      bool is_null (false);
      mysql::value_traits<
          ::TR::Core::Key,
          mysql::id_long >::set_image (
        i.m_key_value, is_null, v);
      i.m_key_null = is_null;
    }

    // m_name
    //
    {
      ::std::string const& v =
        o.m_name;

      bool is_null (false);
      std::size_t size (0);
      std::size_t cap (i.m_name_value.capacity ());
      mysql::value_traits<
          ::std::string,
          mysql::id_string >::set_image (
        i.m_name_value,
        size,
        is_null,
        v);
      i.m_name_null = is_null;
      i.m_name_size = static_cast<unsigned long> (size);
      grew = grew || (cap != i.m_name_value.capacity ());
    }

    // m_input_uuid
    //
    {
      ::TR::Core::ReportTypeUUID const& v =
        o.m_input_uuid;

      if (composite_value_traits< ::TR::Core::ReportTypeUUID, id_mysql >::init (
            i.m_input_uuid_value,
            v,
            sk))
        grew = true;
    }

    // m_output_uuid
    //
    {
      ::TR::Core::ReportTypeUUID const& v =
        o.m_output_uuid;

      if (composite_value_traits< ::TR::Core::ReportTypeUUID, id_mysql >::init (
            i.m_output_uuid_value,
            v,
            sk))
        grew = true;
    }

    return grew;
  }

  void access::object_traits_impl< ::TR::Core::ComplianceData, id_mysql >::
  init (object_type& o,
        const image_type& i,
        database* db)
  {
    ODB_POTENTIALLY_UNUSED (o);
    ODB_POTENTIALLY_UNUSED (i);
    ODB_POTENTIALLY_UNUSED (db);

    // m_key
    //
    {
      ::TR::Core::Key& v =
        o.m_key;

      mysql::value_traits<
          ::TR::Core::Key,
          mysql::id_long >::set_value (
        v,
        i.m_key_value,
        i.m_key_null);
    }

    // m_name
    //
    {
      ::std::string& v =
        o.m_name;

      mysql::value_traits<
          ::std::string,
          mysql::id_string >::set_value (
        v,
        i.m_name_value,
        i.m_name_size,
        i.m_name_null);
    }

    // m_input_uuid
    //
    {
      ::TR::Core::ReportTypeUUID& v =
        o.m_input_uuid;

      composite_value_traits< ::TR::Core::ReportTypeUUID, id_mysql >::init (
        v,
        i.m_input_uuid_value,
        db);
    }

    // m_output_uuid
    //
    {
      ::TR::Core::ReportTypeUUID& v =
        o.m_output_uuid;

      composite_value_traits< ::TR::Core::ReportTypeUUID, id_mysql >::init (
        v,
        i.m_output_uuid_value,
        db);
    }
  }

  void access::object_traits_impl< ::TR::Core::ComplianceData, id_mysql >::
  init (id_image_type& i, const id_type& id)
  {
    {
      bool is_null (false);
      mysql::value_traits<
          ::TR::Core::Key,
          mysql::id_long >::set_image (
        i.id_value, is_null, id);
      i.id_null = is_null;
    }
  }

  const char access::object_traits_impl< ::TR::Core::ComplianceData, id_mysql >::persist_statement[] =
  "INSERT INTO `ComplianceData` "
  "(`key`, "
  "`name`, "
  "`input_uuid_value`, "
  "`output_uuid_value`) "
  "VALUES "
  "(?, ?, ?, ?)";

  const char access::object_traits_impl< ::TR::Core::ComplianceData, id_mysql >::find_statement[] =
  "SELECT "
  "`ComplianceData`.`key`, "
  "`ComplianceData`.`name`, "
  "`ComplianceData`.`input_uuid_value`, "
  "`ComplianceData`.`output_uuid_value` "
  "FROM `ComplianceData` "
  "WHERE `ComplianceData`.`key`=?";

  const char access::object_traits_impl< ::TR::Core::ComplianceData, id_mysql >::update_statement[] =
  "UPDATE `ComplianceData` "
  "SET "
  "`name`=?, "
  "`input_uuid_value`=?, "
  "`output_uuid_value`=? "
  "WHERE `key`=?";

  const char access::object_traits_impl< ::TR::Core::ComplianceData, id_mysql >::erase_statement[] =
  "DELETE FROM `ComplianceData` "
  "WHERE `key`=?";

  const char access::object_traits_impl< ::TR::Core::ComplianceData, id_mysql >::query_statement[] =
  "SELECT "
  "`ComplianceData`.`key`, "
  "`ComplianceData`.`name`, "
  "`ComplianceData`.`input_uuid_value`, "
  "`ComplianceData`.`output_uuid_value` "
  "FROM `ComplianceData`";

  const char access::object_traits_impl< ::TR::Core::ComplianceData, id_mysql >::erase_query_statement[] =
  "DELETE FROM `ComplianceData`";

  const char access::object_traits_impl< ::TR::Core::ComplianceData, id_mysql >::table_name[] =
  "`ComplianceData`";

  void access::object_traits_impl< ::TR::Core::ComplianceData, id_mysql >::
  persist (database& db, const object_type& obj)
  {
    ODB_POTENTIALLY_UNUSED (db);

    using namespace mysql;

    mysql::connection& conn (
      mysql::transaction::current ().connection ());
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    callback (db,
              obj,
              callback_event::pre_persist);

    image_type& im (sts.image ());
    binding& imb (sts.insert_image_binding ());

    if (init (im, obj, statement_insert))
      im.version++;

    if (im.version != sts.insert_image_version () ||
        imb.version == 0)
    {
      bind (imb.bind, im, statement_insert);
      sts.insert_image_version (im.version);
      imb.version++;
    }

    insert_statement& st (sts.persist_statement ());
    if (!st.execute ())
      throw object_already_persistent ();

    callback (db,
              obj,
              callback_event::post_persist);
  }

  void access::object_traits_impl< ::TR::Core::ComplianceData, id_mysql >::
  update (database& db, const object_type& obj)
  {
    ODB_POTENTIALLY_UNUSED (db);

    using namespace mysql;
    using mysql::update_statement;

    callback (db, obj, callback_event::pre_update);

    mysql::transaction& tr (mysql::transaction::current ());
    mysql::connection& conn (tr.connection ());
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    const id_type& id (
      obj.m_key);
    id_image_type& idi (sts.id_image ());
    init (idi, id);

    image_type& im (sts.image ());
    if (init (im, obj, statement_update))
      im.version++;

    bool u (false);
    binding& imb (sts.update_image_binding ());
    if (im.version != sts.update_image_version () ||
        imb.version == 0)
    {
      bind (imb.bind, im, statement_update);
      sts.update_image_version (im.version);
      imb.version++;
      u = true;
    }

    binding& idb (sts.id_image_binding ());
    if (idi.version != sts.update_id_image_version () ||
        idb.version == 0)
    {
      if (idi.version != sts.id_image_version () ||
          idb.version == 0)
      {
        bind (idb.bind, idi);
        sts.id_image_version (idi.version);
        idb.version++;
      }

      sts.update_id_image_version (idi.version);

      if (!u)
        imb.version++;
    }

    update_statement& st (sts.update_statement ());
    if (st.execute () == 0)
      throw object_not_persistent ();

    callback (db, obj, callback_event::post_update);
    pointer_cache_traits::update (db, obj);
  }

  void access::object_traits_impl< ::TR::Core::ComplianceData, id_mysql >::
  erase (database& db, const id_type& id)
  {
    using namespace mysql;

    ODB_POTENTIALLY_UNUSED (db);

    mysql::connection& conn (
      mysql::transaction::current ().connection ());
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    id_image_type& i (sts.id_image ());
    init (i, id);

    binding& idb (sts.id_image_binding ());
    if (i.version != sts.id_image_version () || idb.version == 0)
    {
      bind (idb.bind, i);
      sts.id_image_version (i.version);
      idb.version++;
    }

    if (sts.erase_statement ().execute () != 1)
      throw object_not_persistent ();

    pointer_cache_traits::erase (db, id);
  }

  access::object_traits_impl< ::TR::Core::ComplianceData, id_mysql >::pointer_type
  access::object_traits_impl< ::TR::Core::ComplianceData, id_mysql >::
  find (database& db, const id_type& id)
  {
    using namespace mysql;

    {
      pointer_type p (pointer_cache_traits::find (db, id));

      if (!pointer_traits::null_ptr (p))
        return p;
    }

    mysql::connection& conn (
      mysql::transaction::current ().connection ());
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    statements_type::auto_lock l (sts);

    if (l.locked ())
    {
      if (!find_ (sts, &id))
        return pointer_type ();
    }

    pointer_type p (
      access::object_factory<object_type, pointer_type>::create ());
    pointer_traits::guard pg (p);

    pointer_cache_traits::insert_guard ig (
      pointer_cache_traits::insert (db, id, p));

    object_type& obj (pointer_traits::get_ref (p));

    if (l.locked ())
    {
      select_statement& st (sts.find_statement ());
      ODB_POTENTIALLY_UNUSED (st);

      callback (db, obj, callback_event::pre_load);
      init (obj, sts.image (), &db);
      load_ (sts, obj, false);
      sts.load_delayed (0);
      l.unlock ();
      callback (db, obj, callback_event::post_load);
      pointer_cache_traits::load (ig.position ());
    }
    else
      sts.delay_load (id, obj, ig.position ());

    ig.release ();
    pg.release ();
    return p;
  }

  bool access::object_traits_impl< ::TR::Core::ComplianceData, id_mysql >::
  find (database& db, const id_type& id, object_type& obj)
  {
    using namespace mysql;

    mysql::connection& conn (
      mysql::transaction::current ().connection ());
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    statements_type::auto_lock l (sts);

    if (!find_ (sts, &id))
      return false;

    select_statement& st (sts.find_statement ());
    ODB_POTENTIALLY_UNUSED (st);

    reference_cache_traits::position_type pos (
      reference_cache_traits::insert (db, id, obj));
    reference_cache_traits::insert_guard ig (pos);

    callback (db, obj, callback_event::pre_load);
    init (obj, sts.image (), &db);
    load_ (sts, obj, false);
    sts.load_delayed (0);
    l.unlock ();
    callback (db, obj, callback_event::post_load);
    reference_cache_traits::load (pos);
    ig.release ();
    return true;
  }

  bool access::object_traits_impl< ::TR::Core::ComplianceData, id_mysql >::
  reload (database& db, object_type& obj)
  {
    using namespace mysql;

    mysql::connection& conn (
      mysql::transaction::current ().connection ());
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    statements_type::auto_lock l (sts);

    const id_type& id  (
      obj.m_key);

    if (!find_ (sts, &id))
      return false;

    select_statement& st (sts.find_statement ());
    ODB_POTENTIALLY_UNUSED (st);

    callback (db, obj, callback_event::pre_load);
    init (obj, sts.image (), &db);
    load_ (sts, obj, true);
    sts.load_delayed (0);
    l.unlock ();
    callback (db, obj, callback_event::post_load);
    return true;
  }

  bool access::object_traits_impl< ::TR::Core::ComplianceData, id_mysql >::
  find_ (statements_type& sts,
         const id_type* id)
  {
    using namespace mysql;

    id_image_type& i (sts.id_image ());
    init (i, *id);

    binding& idb (sts.id_image_binding ());
    if (i.version != sts.id_image_version () || idb.version == 0)
    {
      bind (idb.bind, i);
      sts.id_image_version (i.version);
      idb.version++;
    }

    image_type& im (sts.image ());
    binding& imb (sts.select_image_binding ());

    if (im.version != sts.select_image_version () ||
        imb.version == 0)
    {
      bind (imb.bind, im, statement_select);
      sts.select_image_version (im.version);
      imb.version++;
    }

    select_statement& st (sts.find_statement ());

    st.execute ();
    auto_result ar (st);
    select_statement::result r (st.fetch ());

    if (r == select_statement::truncated)
    {
      if (grow (im, sts.select_image_truncated ()))
        im.version++;

      if (im.version != sts.select_image_version ())
      {
        bind (imb.bind, im, statement_select);
        sts.select_image_version (im.version);
        imb.version++;
        st.refetch ();
      }
    }

    return r != select_statement::no_data;
  }

  result< access::object_traits_impl< ::TR::Core::ComplianceData, id_mysql >::object_type >
  access::object_traits_impl< ::TR::Core::ComplianceData, id_mysql >::
  query (database&, const query_base_type& q)
  {
    using namespace mysql;
    using odb::details::shared;
    using odb::details::shared_ptr;

    mysql::connection& conn (
      mysql::transaction::current ().connection ());

    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    image_type& im (sts.image ());
    binding& imb (sts.select_image_binding ());

    if (im.version != sts.select_image_version () ||
        imb.version == 0)
    {
      bind (imb.bind, im, statement_select);
      sts.select_image_version (im.version);
      imb.version++;
    }

    std::string text (query_statement);
    if (!q.empty ())
    {
      text += " ";
      text += q.clause ();
    }

    q.init_parameters ();
    shared_ptr<select_statement> st (
      new (shared) select_statement (
        conn,
        text,
        false,
        true,
        q.parameters_binding (),
        imb));

    st->execute ();

    shared_ptr< odb::object_result_impl<object_type> > r (
      new (shared) mysql::object_result_impl<object_type> (
        q, st, sts, 0));

    return result<object_type> (r);
  }

  unsigned long long access::object_traits_impl< ::TR::Core::ComplianceData, id_mysql >::
  erase_query (database&, const query_base_type& q)
  {
    using namespace mysql;

    mysql::connection& conn (
      mysql::transaction::current ().connection ());

    std::string text (erase_query_statement);
    if (!q.empty ())
    {
      text += ' ';
      text += q.clause ();
    }

    q.init_parameters ();
    delete_statement st (
      conn,
      text,
      q.parameters_binding ());

    return st.execute ();
  }

  // SubjectComplianceIdentity
  //

  bool access::composite_value_traits< ::TR::Core::SubjectComplianceIdentity, id_mysql >::
  grow (image_type& i,
        my_bool* t)
  {
    ODB_POTENTIALLY_UNUSED (i);
    ODB_POTENTIALLY_UNUSED (t);

    bool grew (false);

    // m_subject
    //
    if (composite_value_traits< ::TR::Core::SubjectIdentity, id_mysql >::grow (
          i.m_subject_value, t + 0UL))
      grew = true;

    // m_compliance_key
    //
    if (composite_value_traits< ::TR::Core::ComplianceKey, id_mysql >::grow (
          i.m_compliance_key_value, t + 2UL))
      grew = true;

    return grew;
  }

  void access::composite_value_traits< ::TR::Core::SubjectComplianceIdentity, id_mysql >::
  bind (MYSQL_BIND* b,
        image_type& i,
        mysql::statement_kind sk)
  {
    ODB_POTENTIALLY_UNUSED (b);
    ODB_POTENTIALLY_UNUSED (i);
    ODB_POTENTIALLY_UNUSED (sk);

    using namespace mysql;

    std::size_t n (0);
    ODB_POTENTIALLY_UNUSED (n);

    // m_subject
    //
    composite_value_traits< ::TR::Core::SubjectIdentity, id_mysql >::bind (
      b + n, i.m_subject_value, sk);
    n += 2UL;

    // m_compliance_key
    //
    composite_value_traits< ::TR::Core::ComplianceKey, id_mysql >::bind (
      b + n, i.m_compliance_key_value, sk);
    n += 1UL;
  }

  bool access::composite_value_traits< ::TR::Core::SubjectComplianceIdentity, id_mysql >::
  init (image_type& i,
        const value_type& o,
        mysql::statement_kind sk)
  {
    ODB_POTENTIALLY_UNUSED (i);
    ODB_POTENTIALLY_UNUSED (o);
    ODB_POTENTIALLY_UNUSED (sk);

    using namespace mysql;

    bool grew (false);

    // m_subject
    //
    {
      ::TR::Core::SubjectIdentity const& v =
        o.m_subject;

      composite_value_traits< ::TR::Core::SubjectIdentity, id_mysql >::init (
        i.m_subject_value,
        v,
        sk);
    }

    // m_compliance_key
    //
    {
      ::TR::Core::ComplianceKey const& v =
        o.m_compliance_key;

      composite_value_traits< ::TR::Core::ComplianceKey, id_mysql >::init (
        i.m_compliance_key_value,
        v,
        sk);
    }

    return grew;
  }

  void access::composite_value_traits< ::TR::Core::SubjectComplianceIdentity, id_mysql >::
  init (value_type& o,
        const image_type&  i,
        database* db)
  {
    ODB_POTENTIALLY_UNUSED (o);
    ODB_POTENTIALLY_UNUSED (i);
    ODB_POTENTIALLY_UNUSED (db);

    // m_subject
    //
    {
      ::TR::Core::SubjectIdentity& v =
        o.m_subject;

      composite_value_traits< ::TR::Core::SubjectIdentity, id_mysql >::init (
        v,
        i.m_subject_value,
        db);
    }

    // m_compliance_key
    //
    {
      ::TR::Core::ComplianceKey& v =
        o.m_compliance_key;

      composite_value_traits< ::TR::Core::ComplianceKey, id_mysql >::init (
        v,
        i.m_compliance_key_value,
        db);
    }
  }

  // SubjectComplianceData
  //

  struct access::object_traits_impl< ::TR::Core::SubjectComplianceData, id_mysql >::extra_statement_cache_type
  {
    extra_statement_cache_type (
      mysql::connection&,
      image_type&,
      id_image_type&,
      mysql::binding&,
      mysql::binding&)
    {
    }
  };

  access::object_traits_impl< ::TR::Core::SubjectComplianceData, id_mysql >::id_type
  access::object_traits_impl< ::TR::Core::SubjectComplianceData, id_mysql >::
  id (const image_type& i)
  {
    mysql::database* db (0);
    ODB_POTENTIALLY_UNUSED (db);

    id_type id;
    {
      composite_value_traits< ::TR::Core::SubjectComplianceIdentity, id_mysql >::init (
        id,
        i.m_identity_value,
        db);
    }

    return id;
  }

  bool access::object_traits_impl< ::TR::Core::SubjectComplianceData, id_mysql >::
  grow (image_type& i,
        my_bool* t)
  {
    ODB_POTENTIALLY_UNUSED (i);
    ODB_POTENTIALLY_UNUSED (t);

    bool grew (false);

    // m_identity
    //
    if (composite_value_traits< ::TR::Core::SubjectComplianceIdentity, id_mysql >::grow (
          i.m_identity_value, t + 0UL))
      grew = true;

    // m_checking_policy
    //
    t[3UL] = 0;

    // m_checking_result
    //
    t[4UL] = 0;

    // m_input_uuid
    //
    if (t[5UL])
    {
      i.m_input_uuid_value.capacity (i.m_input_uuid_size);
      grew = true;
    }

    return grew;
  }

  void access::object_traits_impl< ::TR::Core::SubjectComplianceData, id_mysql >::
  bind (MYSQL_BIND* b,
        image_type& i,
        mysql::statement_kind sk)
  {
    ODB_POTENTIALLY_UNUSED (sk);

    using namespace mysql;

    std::size_t n (0);

    // m_identity
    //
    if (sk != statement_update)
    {
      composite_value_traits< ::TR::Core::SubjectComplianceIdentity, id_mysql >::bind (
        b + n, i.m_identity_value, sk);
      n += 3UL;
    }

    // m_checking_policy
    //
    b[n].buffer_type = MYSQL_TYPE_LONG;
    b[n].is_unsigned = 0;
    b[n].buffer = &i.m_checking_policy_value;
    b[n].is_null = &i.m_checking_policy_null;
    n++;

    // m_checking_result
    //
    b[n].buffer_type = MYSQL_TYPE_LONG;
    b[n].is_unsigned = 0;
    b[n].buffer = &i.m_checking_result_value;
    b[n].is_null = &i.m_checking_result_null;
    n++;

    // m_input_uuid
    //
    b[n].buffer_type = MYSQL_TYPE_BLOB;
    b[n].buffer = i.m_input_uuid_value.data ();
    b[n].buffer_length = static_cast<unsigned long> (
      i.m_input_uuid_value.capacity ());
    b[n].length = &i.m_input_uuid_size;
    b[n].is_null = &i.m_input_uuid_null;
    n++;
  }

  void access::object_traits_impl< ::TR::Core::SubjectComplianceData, id_mysql >::
  bind (MYSQL_BIND* b, id_image_type& i)
  {
    std::size_t n (0);
    mysql::statement_kind sk (mysql::statement_select);
    composite_value_traits< ::TR::Core::SubjectComplianceIdentity, id_mysql >::bind (
      b + n, i.id_value, sk);
  }

  bool access::object_traits_impl< ::TR::Core::SubjectComplianceData, id_mysql >::
  init (image_type& i,
        const object_type& o,
        mysql::statement_kind sk)
  {
    ODB_POTENTIALLY_UNUSED (i);
    ODB_POTENTIALLY_UNUSED (o);
    ODB_POTENTIALLY_UNUSED (sk);

    using namespace mysql;

    bool grew (false);

    // m_identity
    //
    if (sk == statement_insert)
    {
      ::TR::Core::SubjectComplianceIdentity const& v =
        o.m_identity;

      composite_value_traits< ::TR::Core::SubjectComplianceIdentity, id_mysql >::init (
        i.m_identity_value,
        v,
        sk);
    }

    // m_checking_policy
    //
    {
      ::TR::Core::ComplianceCheckingPolicy const& v =
        o.m_checking_policy;

      bool is_null (false);
      mysql::value_traits<
          ::TR::Core::ComplianceCheckingPolicy,
          mysql::id_long >::set_image (
        i.m_checking_policy_value, is_null, v);
      i.m_checking_policy_null = is_null;
    }

    // m_checking_result
    //
    {
      ::TR::Core::ComplianceCheckingResult const& v =
        o.m_checking_result;

      bool is_null (false);
      mysql::value_traits<
          ::TR::Core::ComplianceCheckingResult,
          mysql::id_long >::set_image (
        i.m_checking_result_value, is_null, v);
      i.m_checking_result_null = is_null;
    }

    // m_input_uuid
    //
    {
      ::TR::Core::UUID const& v =
        o.m_input_uuid;

      bool is_null (true);
      std::size_t size (0);
      std::size_t cap (i.m_input_uuid_value.capacity ());
      mysql::value_traits<
          ::TR::Core::UUID,
          mysql::id_blob >::set_image (
        i.m_input_uuid_value,
        size,
        is_null,
        v);
      i.m_input_uuid_null = is_null;
      i.m_input_uuid_size = static_cast<unsigned long> (size);
      grew = grew || (cap != i.m_input_uuid_value.capacity ());
    }

    return grew;
  }

  void access::object_traits_impl< ::TR::Core::SubjectComplianceData, id_mysql >::
  init (object_type& o,
        const image_type& i,
        database* db)
  {
    ODB_POTENTIALLY_UNUSED (o);
    ODB_POTENTIALLY_UNUSED (i);
    ODB_POTENTIALLY_UNUSED (db);

    // m_identity
    //
    {
      ::TR::Core::SubjectComplianceIdentity& v =
        o.m_identity;

      composite_value_traits< ::TR::Core::SubjectComplianceIdentity, id_mysql >::init (
        v,
        i.m_identity_value,
        db);
    }

    // m_checking_policy
    //
    {
      ::TR::Core::ComplianceCheckingPolicy& v =
        o.m_checking_policy;

      mysql::value_traits<
          ::TR::Core::ComplianceCheckingPolicy,
          mysql::id_long >::set_value (
        v,
        i.m_checking_policy_value,
        i.m_checking_policy_null);
    }

    // m_checking_result
    //
    {
      ::TR::Core::ComplianceCheckingResult& v =
        o.m_checking_result;

      mysql::value_traits<
          ::TR::Core::ComplianceCheckingResult,
          mysql::id_long >::set_value (
        v,
        i.m_checking_result_value,
        i.m_checking_result_null);
    }

    // m_input_uuid
    //
    {
      ::TR::Core::UUID& v =
        o.m_input_uuid;

      mysql::value_traits<
          ::TR::Core::UUID,
          mysql::id_blob >::set_value (
        v,
        i.m_input_uuid_value,
        i.m_input_uuid_size,
        i.m_input_uuid_null);
    }
  }

  void access::object_traits_impl< ::TR::Core::SubjectComplianceData, id_mysql >::
  init (id_image_type& i, const id_type& id)
  {
    mysql::statement_kind sk (mysql::statement_select);
    {
      composite_value_traits< ::TR::Core::SubjectComplianceIdentity, id_mysql >::init (
        i.id_value,
        id,
        sk);
    }
  }

  const char access::object_traits_impl< ::TR::Core::SubjectComplianceData, id_mysql >::persist_statement[] =
  "INSERT INTO `SubjectComplianceData` "
  "(`identity_subject_value1_value`, "
  "`identity_subject_value2_value`, "
  "`identity_compliance_key_value`, "
  "`checking_policy`, "
  "`checking_result`, "
  "`input_uuid`) "
  "VALUES "
  "(?, ?, ?, ?, ?, ?)";

  const char access::object_traits_impl< ::TR::Core::SubjectComplianceData, id_mysql >::find_statement[] =
  "SELECT "
  "`SubjectComplianceData`.`identity_subject_value1_value`, "
  "`SubjectComplianceData`.`identity_subject_value2_value`, "
  "`SubjectComplianceData`.`identity_compliance_key_value`, "
  "`SubjectComplianceData`.`checking_policy`, "
  "`SubjectComplianceData`.`checking_result`, "
  "`SubjectComplianceData`.`input_uuid` "
  "FROM `SubjectComplianceData` "
  "WHERE `SubjectComplianceData`.`identity_subject_value1_value`=? AND `SubjectComplianceData`.`identity_subject_value2_value`=? AND `SubjectComplianceData`.`identity_compliance_key_value`=?";

  const char access::object_traits_impl< ::TR::Core::SubjectComplianceData, id_mysql >::update_statement[] =
  "UPDATE `SubjectComplianceData` "
  "SET "
  "`checking_policy`=?, "
  "`checking_result`=?, "
  "`input_uuid`=? "
  "WHERE `identity_subject_value1_value`=? AND `identity_subject_value2_value`=? AND `identity_compliance_key_value`=?";

  const char access::object_traits_impl< ::TR::Core::SubjectComplianceData, id_mysql >::erase_statement[] =
  "DELETE FROM `SubjectComplianceData` "
  "WHERE `identity_subject_value1_value`=? AND `identity_subject_value2_value`=? AND `identity_compliance_key_value`=?";

  const char access::object_traits_impl< ::TR::Core::SubjectComplianceData, id_mysql >::query_statement[] =
  "SELECT "
  "`SubjectComplianceData`.`identity_subject_value1_value`, "
  "`SubjectComplianceData`.`identity_subject_value2_value`, "
  "`SubjectComplianceData`.`identity_compliance_key_value`, "
  "`SubjectComplianceData`.`checking_policy`, "
  "`SubjectComplianceData`.`checking_result`, "
  "`SubjectComplianceData`.`input_uuid` "
  "FROM `SubjectComplianceData`";

  const char access::object_traits_impl< ::TR::Core::SubjectComplianceData, id_mysql >::erase_query_statement[] =
  "DELETE FROM `SubjectComplianceData`";

  const char access::object_traits_impl< ::TR::Core::SubjectComplianceData, id_mysql >::table_name[] =
  "`SubjectComplianceData`";

  void access::object_traits_impl< ::TR::Core::SubjectComplianceData, id_mysql >::
  persist (database& db, const object_type& obj)
  {
    ODB_POTENTIALLY_UNUSED (db);

    using namespace mysql;

    mysql::connection& conn (
      mysql::transaction::current ().connection ());
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    callback (db,
              obj,
              callback_event::pre_persist);

    image_type& im (sts.image ());
    binding& imb (sts.insert_image_binding ());

    if (init (im, obj, statement_insert))
      im.version++;

    if (im.version != sts.insert_image_version () ||
        imb.version == 0)
    {
      bind (imb.bind, im, statement_insert);
      sts.insert_image_version (im.version);
      imb.version++;
    }

    insert_statement& st (sts.persist_statement ());
    if (!st.execute ())
      throw object_already_persistent ();

    callback (db,
              obj,
              callback_event::post_persist);
  }

  void access::object_traits_impl< ::TR::Core::SubjectComplianceData, id_mysql >::
  update (database& db, const object_type& obj)
  {
    ODB_POTENTIALLY_UNUSED (db);

    using namespace mysql;
    using mysql::update_statement;

    callback (db, obj, callback_event::pre_update);

    mysql::transaction& tr (mysql::transaction::current ());
    mysql::connection& conn (tr.connection ());
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    const id_type& id (
      obj.m_identity);
    id_image_type& idi (sts.id_image ());
    init (idi, id);

    image_type& im (sts.image ());
    if (init (im, obj, statement_update))
      im.version++;

    bool u (false);
    binding& imb (sts.update_image_binding ());
    if (im.version != sts.update_image_version () ||
        imb.version == 0)
    {
      bind (imb.bind, im, statement_update);
      sts.update_image_version (im.version);
      imb.version++;
      u = true;
    }

    binding& idb (sts.id_image_binding ());
    if (idi.version != sts.update_id_image_version () ||
        idb.version == 0)
    {
      if (idi.version != sts.id_image_version () ||
          idb.version == 0)
      {
        bind (idb.bind, idi);
        sts.id_image_version (idi.version);
        idb.version++;
      }

      sts.update_id_image_version (idi.version);

      if (!u)
        imb.version++;
    }

    update_statement& st (sts.update_statement ());
    if (st.execute () == 0)
      throw object_not_persistent ();

    callback (db, obj, callback_event::post_update);
    pointer_cache_traits::update (db, obj);
  }

  void access::object_traits_impl< ::TR::Core::SubjectComplianceData, id_mysql >::
  erase (database& db, const id_type& id)
  {
    using namespace mysql;

    ODB_POTENTIALLY_UNUSED (db);

    mysql::connection& conn (
      mysql::transaction::current ().connection ());
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    id_image_type& i (sts.id_image ());
    init (i, id);

    binding& idb (sts.id_image_binding ());
    if (i.version != sts.id_image_version () || idb.version == 0)
    {
      bind (idb.bind, i);
      sts.id_image_version (i.version);
      idb.version++;
    }

    if (sts.erase_statement ().execute () != 1)
      throw object_not_persistent ();

    pointer_cache_traits::erase (db, id);
  }

  access::object_traits_impl< ::TR::Core::SubjectComplianceData, id_mysql >::pointer_type
  access::object_traits_impl< ::TR::Core::SubjectComplianceData, id_mysql >::
  find (database& db, const id_type& id)
  {
    using namespace mysql;

    {
      pointer_type p (pointer_cache_traits::find (db, id));

      if (!pointer_traits::null_ptr (p))
        return p;
    }

    mysql::connection& conn (
      mysql::transaction::current ().connection ());
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    statements_type::auto_lock l (sts);

    if (l.locked ())
    {
      if (!find_ (sts, &id))
        return pointer_type ();
    }

    pointer_type p (
      access::object_factory<object_type, pointer_type>::create ());
    pointer_traits::guard pg (p);

    pointer_cache_traits::insert_guard ig (
      pointer_cache_traits::insert (db, id, p));

    object_type& obj (pointer_traits::get_ref (p));

    if (l.locked ())
    {
      select_statement& st (sts.find_statement ());
      ODB_POTENTIALLY_UNUSED (st);

      callback (db, obj, callback_event::pre_load);
      init (obj, sts.image (), &db);
      load_ (sts, obj, false);
      sts.load_delayed (0);
      l.unlock ();
      callback (db, obj, callback_event::post_load);
      pointer_cache_traits::load (ig.position ());
    }
    else
      sts.delay_load (id, obj, ig.position ());

    ig.release ();
    pg.release ();
    return p;
  }

  bool access::object_traits_impl< ::TR::Core::SubjectComplianceData, id_mysql >::
  find (database& db, const id_type& id, object_type& obj)
  {
    using namespace mysql;

    mysql::connection& conn (
      mysql::transaction::current ().connection ());
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    statements_type::auto_lock l (sts);

    if (!find_ (sts, &id))
      return false;

    select_statement& st (sts.find_statement ());
    ODB_POTENTIALLY_UNUSED (st);

    reference_cache_traits::position_type pos (
      reference_cache_traits::insert (db, id, obj));
    reference_cache_traits::insert_guard ig (pos);

    callback (db, obj, callback_event::pre_load);
    init (obj, sts.image (), &db);
    load_ (sts, obj, false);
    sts.load_delayed (0);
    l.unlock ();
    callback (db, obj, callback_event::post_load);
    reference_cache_traits::load (pos);
    ig.release ();
    return true;
  }

  bool access::object_traits_impl< ::TR::Core::SubjectComplianceData, id_mysql >::
  reload (database& db, object_type& obj)
  {
    using namespace mysql;

    mysql::connection& conn (
      mysql::transaction::current ().connection ());
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    statements_type::auto_lock l (sts);

    const id_type& id  (
      obj.m_identity);

    if (!find_ (sts, &id))
      return false;

    select_statement& st (sts.find_statement ());
    ODB_POTENTIALLY_UNUSED (st);

    callback (db, obj, callback_event::pre_load);
    init (obj, sts.image (), &db);
    load_ (sts, obj, true);
    sts.load_delayed (0);
    l.unlock ();
    callback (db, obj, callback_event::post_load);
    return true;
  }

  bool access::object_traits_impl< ::TR::Core::SubjectComplianceData, id_mysql >::
  find_ (statements_type& sts,
         const id_type* id)
  {
    using namespace mysql;

    id_image_type& i (sts.id_image ());
    init (i, *id);

    binding& idb (sts.id_image_binding ());
    if (i.version != sts.id_image_version () || idb.version == 0)
    {
      bind (idb.bind, i);
      sts.id_image_version (i.version);
      idb.version++;
    }

    image_type& im (sts.image ());
    binding& imb (sts.select_image_binding ());

    if (im.version != sts.select_image_version () ||
        imb.version == 0)
    {
      bind (imb.bind, im, statement_select);
      sts.select_image_version (im.version);
      imb.version++;
    }

    select_statement& st (sts.find_statement ());

    st.execute ();
    auto_result ar (st);
    select_statement::result r (st.fetch ());

    if (r == select_statement::truncated)
    {
      if (grow (im, sts.select_image_truncated ()))
        im.version++;

      if (im.version != sts.select_image_version ())
      {
        bind (imb.bind, im, statement_select);
        sts.select_image_version (im.version);
        imb.version++;
        st.refetch ();
      }
    }

    return r != select_statement::no_data;
  }

  result< access::object_traits_impl< ::TR::Core::SubjectComplianceData, id_mysql >::object_type >
  access::object_traits_impl< ::TR::Core::SubjectComplianceData, id_mysql >::
  query (database&, const query_base_type& q)
  {
    using namespace mysql;
    using odb::details::shared;
    using odb::details::shared_ptr;

    mysql::connection& conn (
      mysql::transaction::current ().connection ());

    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    image_type& im (sts.image ());
    binding& imb (sts.select_image_binding ());

    if (im.version != sts.select_image_version () ||
        imb.version == 0)
    {
      bind (imb.bind, im, statement_select);
      sts.select_image_version (im.version);
      imb.version++;
    }

    std::string text (query_statement);
    if (!q.empty ())
    {
      text += " ";
      text += q.clause ();
    }

    q.init_parameters ();
    shared_ptr<select_statement> st (
      new (shared) select_statement (
        conn,
        text,
        false,
        true,
        q.parameters_binding (),
        imb));

    st->execute ();

    shared_ptr< odb::object_result_impl<object_type> > r (
      new (shared) mysql::object_result_impl<object_type> (
        q, st, sts, 0));

    return result<object_type> (r);
  }

  unsigned long long access::object_traits_impl< ::TR::Core::SubjectComplianceData, id_mysql >::
  erase_query (database&, const query_base_type& q)
  {
    using namespace mysql;

    mysql::connection& conn (
      mysql::transaction::current ().connection ());

    std::string text (erase_query_statement);
    if (!q.empty ())
    {
      text += ' ';
      text += q.clause ();
    }

    q.init_parameters ();
    delete_statement st (
      conn,
      text,
      q.parameters_binding ());

    return st.execute ();
  }
}

namespace odb
{
  static bool
  create_schema (database& db, unsigned short pass, bool drop)
  {
    ODB_POTENTIALLY_UNUSED (db);
    ODB_POTENTIALLY_UNUSED (pass);
    ODB_POTENTIALLY_UNUSED (drop);

    if (drop)
    {
      switch (pass)
      {
        case 1:
        {
          return true;
        }
        case 2:
        {
          db.execute ("DROP TABLE IF EXISTS `SubjectComplianceData`");
          db.execute ("DROP TABLE IF EXISTS `ComplianceData`");
          return false;
        }
      }
    }
    else
    {
      switch (pass)
      {
        case 1:
        {
          db.execute ("CREATE TABLE `ComplianceData` (\n"
                      "  `key` INT NOT NULL PRIMARY KEY,\n"
                      "  `name` TEXT NOT NULL,\n"
                      "  `input_uuid_value` BINARY(16) NULL,\n"
                      "  `output_uuid_value` BINARY(16) NULL)\n"
                      " ENGINE=InnoDB");
          db.execute ("CREATE TABLE `SubjectComplianceData` (\n"
                      "  `identity_subject_value1_value` INT NOT NULL,\n"
                      "  `identity_subject_value2_value` INT NOT NULL,\n"
                      "  `identity_compliance_key_value` INT NOT NULL,\n"
                      "  `checking_policy` INT NOT NULL,\n"
                      "  `checking_result` INT NOT NULL,\n"
                      "  `input_uuid` BINARY(16) NULL,\n"
                      "  PRIMARY KEY (`identity_subject_value1_value`,\n"
                      "               `identity_subject_value2_value`,\n"
                      "               `identity_compliance_key_value`))\n"
                      " ENGINE=InnoDB");
          return false;
        }
      }
    }

    return false;
  }

  static const schema_catalog_create_entry
  create_schema_entry_ (
    id_mysql,
    "",
    &create_schema);
}

#include <odb/post.hxx>
