// This file was generated by ODB, object-relational mapping (ORM)
// compiler for C++.
//

#include <odb/pre.hxx>

#include "CustomQueryData-odb.hxx"

#include <cassert>
#include <cstring>  // std::memcpy

#include <odb/schema-catalog-impl.hxx>

#include <odb/mysql/traits.hxx>
#include <odb/mysql/database.hxx>
#include <odb/mysql/transaction.hxx>
#include <odb/mysql/connection.hxx>
#include <odb/mysql/statement.hxx>
#include <odb/mysql/statement-cache.hxx>
#include <odb/mysql/simple-object-statements.hxx>
#include <odb/mysql/container-statements.hxx>
#include <odb/mysql/exceptions.hxx>
#include <odb/mysql/simple-object-result.hxx>
#include <odb/mysql/enum.hxx>

namespace odb
{
  // CustomQueryData
  //

  struct access::object_traits_impl< ::TR::Core::CustomQueryData, id_mysql >::extra_statement_cache_type
  {
    mysql::container_statements_impl< input_uuids_traits > m_input_uuids;

    extra_statement_cache_type (
      mysql::connection& c,
      image_type&,
      id_image_type&,
      mysql::binding& id,
      mysql::binding&)
    : m_input_uuids (c, id)
    {
    }
  };

  // m_input_uuids
  //

  const char access::object_traits_impl< ::TR::Core::CustomQueryData, id_mysql >::input_uuids_traits::
  select_statement[] =
  "SELECT "
  "`CustomQueryData_input_uuids`.`index`, "
  "`CustomQueryData_input_uuids`.`value_value` "
  "FROM `CustomQueryData_input_uuids` "
  "WHERE `CustomQueryData_input_uuids`.`object_id`=? ORDER BY `CustomQueryData_input_uuids`.`index`";

  const char access::object_traits_impl< ::TR::Core::CustomQueryData, id_mysql >::input_uuids_traits::
  insert_statement[] =
  "INSERT INTO `CustomQueryData_input_uuids` "
  "(`object_id`, "
  "`index`, "
  "`value_value`) "
  "VALUES "
  "(?, ?, ?)";

  const char access::object_traits_impl< ::TR::Core::CustomQueryData, id_mysql >::input_uuids_traits::
  delete_statement[] =
  "DELETE FROM `CustomQueryData_input_uuids` "
  "WHERE `object_id`=?";

  void access::object_traits_impl< ::TR::Core::CustomQueryData, id_mysql >::input_uuids_traits::
  bind (MYSQL_BIND* b,
        const MYSQL_BIND* id,
        std::size_t id_size,
        data_image_type& d)
  {
    using namespace mysql;

    statement_kind sk (statement_select);
    ODB_POTENTIALLY_UNUSED (sk);

    size_t n (0);

    // object_id
    //
    if (id != 0)
      std::memcpy (&b[n], id, id_size * sizeof (id[0]));
    n += id_size;

    // index
    //
    b[n].buffer_type = MYSQL_TYPE_LONGLONG;
    b[n].is_unsigned = 1;
    b[n].buffer = &d.index_value;
    b[n].is_null = &d.index_null;
    n++;

    // value
    //
    composite_value_traits< value_type, id_mysql >::bind (
      b + n, d.value_value, sk);
  }

  void access::object_traits_impl< ::TR::Core::CustomQueryData, id_mysql >::input_uuids_traits::
  grow (data_image_type& i,
        my_bool* t)
  {
    bool grew (false);

    // index
    //
    t[0UL] = 0;

    // value
    //
    if (composite_value_traits< value_type, id_mysql >::grow (
          i.value_value, t + 1UL))
      grew = true;

    if (grew)
      i.version++;
  }

  void access::object_traits_impl< ::TR::Core::CustomQueryData, id_mysql >::input_uuids_traits::
  init (data_image_type& i,
        index_type* j,
        const value_type& v)
  {
    using namespace mysql;

    statement_kind sk (statement_insert);
    ODB_POTENTIALLY_UNUSED (sk);

    bool grew (false);

    // index
    //
    if (j != 0)
    {
      bool is_null (false);
      mysql::value_traits<
          index_type,
          mysql::id_ulonglong >::set_image (
        i.index_value, is_null, *j);
      i.index_null = is_null;
    }

    // value
    //
    {
      if (composite_value_traits< value_type, id_mysql >::init (
            i.value_value,
            v,
            sk))
        grew = true;
    }

    if (grew)
      i.version++;
  }

  void access::object_traits_impl< ::TR::Core::CustomQueryData, id_mysql >::input_uuids_traits::
  init (index_type& j,
        value_type& v,
        const data_image_type& i,
        database* db)
  {
    ODB_POTENTIALLY_UNUSED (db);

    // index
    //
    {
      mysql::value_traits<
          index_type,
          mysql::id_ulonglong >::set_value (
        j,
        i.index_value,
        i.index_null);
    }

    // value
    //
    {
      composite_value_traits< value_type, id_mysql >::init (
        v,
        i.value_value,
        db);
    }
  }

  void access::object_traits_impl< ::TR::Core::CustomQueryData, id_mysql >::input_uuids_traits::
  insert (index_type i, const value_type& v, void* d)
  {
    using namespace mysql;

    statements_type& sts (*static_cast< statements_type* > (d));
    data_image_type& di (sts.data_image ());

    init (di, &i, v);

    if (sts.data_binding_test_version ())
    {
      const binding& id (sts.id_binding ());
      bind (sts.data_bind (), id.bind, id.count, di);
      sts.data_binding_update_version ();
    }

    if (!sts.insert_statement ().execute ())
      throw object_already_persistent ();
  }

  bool access::object_traits_impl< ::TR::Core::CustomQueryData, id_mysql >::input_uuids_traits::
  select (index_type& i, value_type& v, void* d)
  {
    using namespace mysql;
    using mysql::select_statement;

    statements_type& sts (*static_cast< statements_type* > (d));
    data_image_type& di (sts.data_image ());

    init (i, v, di, &sts.connection ().database ());

    select_statement& st (sts.select_statement ());
    select_statement::result r (st.fetch ());

    if (r == select_statement::truncated)
    {
      grow (di, sts.select_image_truncated ());

      if (sts.data_binding_test_version ())
      {
        bind (sts.data_bind (), 0, sts.id_binding ().count, di);
        sts.data_binding_update_version ();
        st.refetch ();
      }
    }

    return r != select_statement::no_data;
  }

  void access::object_traits_impl< ::TR::Core::CustomQueryData, id_mysql >::input_uuids_traits::
  delete_ (void* d)
  {
    using namespace mysql;

    statements_type& sts (*static_cast< statements_type* > (d));
    sts.delete_statement ().execute ();
  }

  void access::object_traits_impl< ::TR::Core::CustomQueryData, id_mysql >::input_uuids_traits::
  persist (const container_type& c,
           statements_type& sts)
  {
    using namespace mysql;

    functions_type& fs (sts.functions ());
    fs.ordered_ = true;
    container_traits_type::persist (c, fs);
  }

  void access::object_traits_impl< ::TR::Core::CustomQueryData, id_mysql >::input_uuids_traits::
  load (container_type& c,
        statements_type& sts)
  {
    using namespace mysql;
    using mysql::select_statement;

    const binding& id (sts.id_binding ());

    if (sts.data_binding_test_version ())
    {
      bind (sts.data_bind (), id.bind, id.count, sts.data_image ());
      sts.data_binding_update_version ();
    }

    select_statement& st (sts.select_statement ());
    st.execute ();
    auto_result ar (st);
    select_statement::result r (st.fetch ());

    if (r == select_statement::truncated)
    {
      data_image_type& di (sts.data_image ());
      grow (di, sts.select_image_truncated ());

      if (sts.data_binding_test_version ())
      {
        bind (sts.data_bind (), 0, id.count, di);
        sts.data_binding_update_version ();
        st.refetch ();
      }
    }

    bool more (r != select_statement::no_data);

    functions_type& fs (sts.functions ());
    fs.ordered_ = true;
    container_traits_type::load (c, more, fs);
  }

  void access::object_traits_impl< ::TR::Core::CustomQueryData, id_mysql >::input_uuids_traits::
  update (const container_type& c,
          statements_type& sts)
  {
    using namespace mysql;

    functions_type& fs (sts.functions ());
    fs.ordered_ = true;
    container_traits_type::update (c, fs);
  }

  void access::object_traits_impl< ::TR::Core::CustomQueryData, id_mysql >::input_uuids_traits::
  erase (statements_type& sts)
  {
    using namespace mysql;

    functions_type& fs (sts.functions ());
    fs.ordered_ = true;
    container_traits_type::erase (fs);
  }

  access::object_traits_impl< ::TR::Core::CustomQueryData, id_mysql >::id_type
  access::object_traits_impl< ::TR::Core::CustomQueryData, id_mysql >::
  id (const id_image_type& i)
  {
    mysql::database* db (0);
    ODB_POTENTIALLY_UNUSED (db);

    id_type id;
    {
      mysql::value_traits<
          ::TR::Core::Key,
          mysql::id_long >::set_value (
        id,
        i.id_value,
        i.id_null);
    }

    return id;
  }

  access::object_traits_impl< ::TR::Core::CustomQueryData, id_mysql >::id_type
  access::object_traits_impl< ::TR::Core::CustomQueryData, id_mysql >::
  id (const image_type& i)
  {
    mysql::database* db (0);
    ODB_POTENTIALLY_UNUSED (db);

    id_type id;
    {
      mysql::value_traits<
          ::TR::Core::Key,
          mysql::id_long >::set_value (
        id,
        i.m_key_value,
        i.m_key_null);
    }

    return id;
  }

  bool access::object_traits_impl< ::TR::Core::CustomQueryData, id_mysql >::
  grow (image_type& i,
        my_bool* t)
  {
    ODB_POTENTIALLY_UNUSED (i);
    ODB_POTENTIALLY_UNUSED (t);

    bool grew (false);

    // m_key
    //
    t[0UL] = 0;

    // m_name
    //
    if (t[1UL])
    {
      i.m_name_value.capacity (i.m_name_size);
      grew = true;
    }

    // m_query_doc
    //
    if (composite_value_traits< ::TR::Core::XmlQueryDocText, id_mysql >::grow (
          i.m_query_doc_value, t + 2UL))
      grew = true;

    // m_query_def
    //
    if (composite_value_traits< ::TR::Core::XmlDefDocText, id_mysql >::grow (
          i.m_query_def_value, t + 3UL))
      grew = true;

    // m_output_uuid
    //
    if (composite_value_traits< ::TR::Core::ReportTypeUUID, id_mysql >::grow (
          i.m_output_uuid_value, t + 4UL))
      grew = true;

    // m_output_def
    //
    if (composite_value_traits< ::TR::Core::XmlDefDocText, id_mysql >::grow (
          i.m_output_def_value, t + 5UL))
      grew = true;

    // m_output_traits
    //
    t[6UL] = 0;

    return grew;
  }

  void access::object_traits_impl< ::TR::Core::CustomQueryData, id_mysql >::
  bind (MYSQL_BIND* b,
        image_type& i,
        mysql::statement_kind sk)
  {
    ODB_POTENTIALLY_UNUSED (sk);

    using namespace mysql;

    std::size_t n (0);

    // m_key
    //
    if (sk != statement_update)
    {
      b[n].buffer_type = MYSQL_TYPE_LONG;
      b[n].is_unsigned = 0;
      b[n].buffer = &i.m_key_value;
      b[n].is_null = &i.m_key_null;
      n++;
    }

    // m_name
    //
    b[n].buffer_type = MYSQL_TYPE_STRING;
    b[n].buffer = i.m_name_value.data ();
    b[n].buffer_length = static_cast<unsigned long> (
      i.m_name_value.capacity ());
    b[n].length = &i.m_name_size;
    b[n].is_null = &i.m_name_null;
    n++;

    // m_query_doc
    //
    composite_value_traits< ::TR::Core::XmlQueryDocText, id_mysql >::bind (
      b + n, i.m_query_doc_value, sk);
    n += 1UL;

    // m_query_def
    //
    composite_value_traits< ::TR::Core::XmlDefDocText, id_mysql >::bind (
      b + n, i.m_query_def_value, sk);
    n += 1UL;

    // m_output_uuid
    //
    composite_value_traits< ::TR::Core::ReportTypeUUID, id_mysql >::bind (
      b + n, i.m_output_uuid_value, sk);
    n += 1UL;

    // m_output_def
    //
    composite_value_traits< ::TR::Core::XmlDefDocText, id_mysql >::bind (
      b + n, i.m_output_def_value, sk);
    n += 1UL;

    // m_output_traits
    //
    b[n].buffer_type = MYSQL_TYPE_LONG;
    b[n].is_unsigned = 0;
    b[n].buffer = &i.m_output_traits_value;
    b[n].is_null = &i.m_output_traits_null;
    n++;
  }

  void access::object_traits_impl< ::TR::Core::CustomQueryData, id_mysql >::
  bind (MYSQL_BIND* b, id_image_type& i)
  {
    std::size_t n (0);
    b[n].buffer_type = MYSQL_TYPE_LONG;
    b[n].is_unsigned = 0;
    b[n].buffer = &i.id_value;
    b[n].is_null = &i.id_null;
  }

  bool access::object_traits_impl< ::TR::Core::CustomQueryData, id_mysql >::
  init (image_type& i,
        const object_type& o,
        mysql::statement_kind sk)
  {
    ODB_POTENTIALLY_UNUSED (i);
    ODB_POTENTIALLY_UNUSED (o);
    ODB_POTENTIALLY_UNUSED (sk);

    using namespace mysql;

    bool grew (false);

    // m_key
    //
    if (sk == statement_insert)
    {
      ::TR::Core::Key const& v =
        o.m_key;

      bool is_null (false);
      mysql::value_traits<
          ::TR::Core::Key,
          mysql::id_long >::set_image (
        i.m_key_value, is_null, v);
      i.m_key_null = is_null;
    }

    // m_name
    //
    {
      ::std::string const& v =
        o.m_name;

      bool is_null (false);
      std::size_t size (0);
      std::size_t cap (i.m_name_value.capacity ());
      mysql::value_traits<
          ::std::string,
          mysql::id_string >::set_image (
        i.m_name_value,
        size,
        is_null,
        v);
      i.m_name_null = is_null;
      i.m_name_size = static_cast<unsigned long> (size);
      grew = grew || (cap != i.m_name_value.capacity ());
    }

    // m_query_doc
    //
    {
      ::TR::Core::XmlQueryDocText const& v =
        o.m_query_doc;

      if (composite_value_traits< ::TR::Core::XmlQueryDocText, id_mysql >::init (
            i.m_query_doc_value,
            v,
            sk))
        grew = true;
    }

    // m_query_def
    //
    {
      ::TR::Core::XmlDefDocText const& v =
        o.m_query_def;

      if (composite_value_traits< ::TR::Core::XmlDefDocText, id_mysql >::init (
            i.m_query_def_value,
            v,
            sk))
        grew = true;
    }

    // m_output_uuid
    //
    {
      ::TR::Core::ReportTypeUUID const& v =
        o.m_output_uuid;

      if (composite_value_traits< ::TR::Core::ReportTypeUUID, id_mysql >::init (
            i.m_output_uuid_value,
            v,
            sk))
        grew = true;
    }

    // m_output_def
    //
    {
      ::TR::Core::XmlDefDocText const& v =
        o.m_output_def;

      if (composite_value_traits< ::TR::Core::XmlDefDocText, id_mysql >::init (
            i.m_output_def_value,
            v,
            sk))
        grew = true;
    }

    // m_output_traits
    //
    {
      int const& v =
        o.m_output_traits;

      bool is_null (false);
      mysql::value_traits<
          int,
          mysql::id_long >::set_image (
        i.m_output_traits_value, is_null, v);
      i.m_output_traits_null = is_null;
    }

    return grew;
  }

  void access::object_traits_impl< ::TR::Core::CustomQueryData, id_mysql >::
  init (object_type& o,
        const image_type& i,
        database* db)
  {
    ODB_POTENTIALLY_UNUSED (o);
    ODB_POTENTIALLY_UNUSED (i);
    ODB_POTENTIALLY_UNUSED (db);

    // m_key
    //
    {
      ::TR::Core::Key& v =
        o.m_key;

      mysql::value_traits<
          ::TR::Core::Key,
          mysql::id_long >::set_value (
        v,
        i.m_key_value,
        i.m_key_null);
    }

    // m_name
    //
    {
      ::std::string& v =
        o.m_name;

      mysql::value_traits<
          ::std::string,
          mysql::id_string >::set_value (
        v,
        i.m_name_value,
        i.m_name_size,
        i.m_name_null);
    }

    // m_query_doc
    //
    {
      ::TR::Core::XmlQueryDocText& v =
        o.m_query_doc;

      composite_value_traits< ::TR::Core::XmlQueryDocText, id_mysql >::init (
        v,
        i.m_query_doc_value,
        db);
    }

    // m_query_def
    //
    {
      ::TR::Core::XmlDefDocText& v =
        o.m_query_def;

      composite_value_traits< ::TR::Core::XmlDefDocText, id_mysql >::init (
        v,
        i.m_query_def_value,
        db);
    }

    // m_output_uuid
    //
    {
      ::TR::Core::ReportTypeUUID& v =
        o.m_output_uuid;

      composite_value_traits< ::TR::Core::ReportTypeUUID, id_mysql >::init (
        v,
        i.m_output_uuid_value,
        db);
    }

    // m_output_def
    //
    {
      ::TR::Core::XmlDefDocText& v =
        o.m_output_def;

      composite_value_traits< ::TR::Core::XmlDefDocText, id_mysql >::init (
        v,
        i.m_output_def_value,
        db);
    }

    // m_output_traits
    //
    {
      int& v =
        o.m_output_traits;

      mysql::value_traits<
          int,
          mysql::id_long >::set_value (
        v,
        i.m_output_traits_value,
        i.m_output_traits_null);
    }
  }

  void access::object_traits_impl< ::TR::Core::CustomQueryData, id_mysql >::
  init (id_image_type& i, const id_type& id)
  {
    {
      bool is_null (false);
      mysql::value_traits<
          ::TR::Core::Key,
          mysql::id_long >::set_image (
        i.id_value, is_null, id);
      i.id_null = is_null;
    }
  }

  const char access::object_traits_impl< ::TR::Core::CustomQueryData, id_mysql >::persist_statement[] =
  "INSERT INTO `CustomQueryData` "
  "(`key`, "
  "`name`, "
  "`query_doc_value`, "
  "`query_def_value`, "
  "`output_uuid_value`, "
  "`output_def_value`, "
  "`output_traits`) "
  "VALUES "
  "(?, ?, ?, ?, ?, ?, ?)";

  const char access::object_traits_impl< ::TR::Core::CustomQueryData, id_mysql >::find_statement[] =
  "SELECT "
  "`CustomQueryData`.`key`, "
  "`CustomQueryData`.`name`, "
  "`CustomQueryData`.`query_doc_value`, "
  "`CustomQueryData`.`query_def_value`, "
  "`CustomQueryData`.`output_uuid_value`, "
  "`CustomQueryData`.`output_def_value`, "
  "`CustomQueryData`.`output_traits` "
  "FROM `CustomQueryData` "
  "WHERE `CustomQueryData`.`key`=?";

  const char access::object_traits_impl< ::TR::Core::CustomQueryData, id_mysql >::update_statement[] =
  "UPDATE `CustomQueryData` "
  "SET "
  "`name`=?, "
  "`query_doc_value`=?, "
  "`query_def_value`=?, "
  "`output_uuid_value`=?, "
  "`output_def_value`=?, "
  "`output_traits`=? "
  "WHERE `key`=?";

  const char access::object_traits_impl< ::TR::Core::CustomQueryData, id_mysql >::erase_statement[] =
  "DELETE FROM `CustomQueryData` "
  "WHERE `key`=?";

  const char access::object_traits_impl< ::TR::Core::CustomQueryData, id_mysql >::query_statement[] =
  "SELECT "
  "`CustomQueryData`.`key`, "
  "`CustomQueryData`.`name`, "
  "`CustomQueryData`.`query_doc_value`, "
  "`CustomQueryData`.`query_def_value`, "
  "`CustomQueryData`.`output_uuid_value`, "
  "`CustomQueryData`.`output_def_value`, "
  "`CustomQueryData`.`output_traits` "
  "FROM `CustomQueryData`";

  const char access::object_traits_impl< ::TR::Core::CustomQueryData, id_mysql >::erase_query_statement[] =
  "DELETE FROM `CustomQueryData`";

  const char access::object_traits_impl< ::TR::Core::CustomQueryData, id_mysql >::table_name[] =
  "`CustomQueryData`";

  void access::object_traits_impl< ::TR::Core::CustomQueryData, id_mysql >::
  persist (database& db, object_type& obj)
  {
    ODB_POTENTIALLY_UNUSED (db);

    using namespace mysql;

    mysql::connection& conn (
      mysql::transaction::current ().connection ());
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    callback (db,
              static_cast<const object_type&> (obj),
              callback_event::pre_persist);

    image_type& im (sts.image ());
    binding& imb (sts.insert_image_binding ());

    if (init (im, obj, statement_insert))
      im.version++;

    im.m_key_value = 0;

    if (im.version != sts.insert_image_version () ||
        imb.version == 0)
    {
      bind (imb.bind, im, statement_insert);
      sts.insert_image_version (im.version);
      imb.version++;
    }

    {
      id_image_type& i (sts.id_image ());
      binding& b (sts.id_image_binding ());
      if (i.version != sts.id_image_version () || b.version == 0)
      {
        bind (b.bind, i);
        sts.id_image_version (i.version);
        b.version++;
      }
    }

    insert_statement& st (sts.persist_statement ());
    if (!st.execute ())
      throw object_already_persistent ();

    obj.m_key = id (sts.id_image ());

    id_image_type& i (sts.id_image ());
    init (i, obj.m_key);

    binding& idb (sts.id_image_binding ());
    if (i.version != sts.id_image_version () || idb.version == 0)
    {
      bind (idb.bind, i);
      sts.id_image_version (i.version);
      idb.version++;
    }

    extra_statement_cache_type& esc (sts.extra_statement_cache ());

    // m_input_uuids
    //
    {
      ::std::vector< ::TR::Core::ReportTypeUUID > const& v =
        obj.m_input_uuids;

      input_uuids_traits::persist (
        v,
        esc.m_input_uuids);
    }

    callback (db,
              static_cast<const object_type&> (obj),
              callback_event::post_persist);
  }

  void access::object_traits_impl< ::TR::Core::CustomQueryData, id_mysql >::
  update (database& db, const object_type& obj)
  {
    ODB_POTENTIALLY_UNUSED (db);

    using namespace mysql;
    using mysql::update_statement;

    callback (db, obj, callback_event::pre_update);

    mysql::transaction& tr (mysql::transaction::current ());
    mysql::connection& conn (tr.connection ());
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    const id_type& id (
      obj.m_key);
    id_image_type& idi (sts.id_image ());
    init (idi, id);

    image_type& im (sts.image ());
    if (init (im, obj, statement_update))
      im.version++;

    bool u (false);
    binding& imb (sts.update_image_binding ());
    if (im.version != sts.update_image_version () ||
        imb.version == 0)
    {
      bind (imb.bind, im, statement_update);
      sts.update_image_version (im.version);
      imb.version++;
      u = true;
    }

    binding& idb (sts.id_image_binding ());
    if (idi.version != sts.update_id_image_version () ||
        idb.version == 0)
    {
      if (idi.version != sts.id_image_version () ||
          idb.version == 0)
      {
        bind (idb.bind, idi);
        sts.id_image_version (idi.version);
        idb.version++;
      }

      sts.update_id_image_version (idi.version);

      if (!u)
        imb.version++;
    }

    update_statement& st (sts.update_statement ());
    if (st.execute () == 0)
      throw object_not_persistent ();

    extra_statement_cache_type& esc (sts.extra_statement_cache ());

    // m_input_uuids
    //
    {
      ::std::vector< ::TR::Core::ReportTypeUUID > const& v =
        obj.m_input_uuids;

      input_uuids_traits::update (
        v,
        esc.m_input_uuids);
    }

    callback (db, obj, callback_event::post_update);
    pointer_cache_traits::update (db, obj);
  }

  void access::object_traits_impl< ::TR::Core::CustomQueryData, id_mysql >::
  erase (database& db, const id_type& id)
  {
    using namespace mysql;

    ODB_POTENTIALLY_UNUSED (db);

    mysql::connection& conn (
      mysql::transaction::current ().connection ());
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    id_image_type& i (sts.id_image ());
    init (i, id);

    binding& idb (sts.id_image_binding ());
    if (i.version != sts.id_image_version () || idb.version == 0)
    {
      bind (idb.bind, i);
      sts.id_image_version (i.version);
      idb.version++;
    }

    extra_statement_cache_type& esc (sts.extra_statement_cache ());

    // m_input_uuids
    //
    input_uuids_traits::erase (
      esc.m_input_uuids);

    if (sts.erase_statement ().execute () != 1)
      throw object_not_persistent ();

    pointer_cache_traits::erase (db, id);
  }

  access::object_traits_impl< ::TR::Core::CustomQueryData, id_mysql >::pointer_type
  access::object_traits_impl< ::TR::Core::CustomQueryData, id_mysql >::
  find (database& db, const id_type& id)
  {
    using namespace mysql;

    {
      pointer_type p (pointer_cache_traits::find (db, id));

      if (!pointer_traits::null_ptr (p))
        return p;
    }

    mysql::connection& conn (
      mysql::transaction::current ().connection ());
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    statements_type::auto_lock l (sts);

    if (l.locked ())
    {
      if (!find_ (sts, &id))
        return pointer_type ();
    }

    pointer_type p (
      access::object_factory<object_type, pointer_type>::create ());
    pointer_traits::guard pg (p);

    pointer_cache_traits::insert_guard ig (
      pointer_cache_traits::insert (db, id, p));

    object_type& obj (pointer_traits::get_ref (p));

    if (l.locked ())
    {
      select_statement& st (sts.find_statement ());
      ODB_POTENTIALLY_UNUSED (st);

      callback (db, obj, callback_event::pre_load);
      init (obj, sts.image (), &db);
      load_ (sts, obj, false);
      sts.load_delayed (0);
      l.unlock ();
      callback (db, obj, callback_event::post_load);
      pointer_cache_traits::load (ig.position ());
    }
    else
      sts.delay_load (id, obj, ig.position ());

    ig.release ();
    pg.release ();
    return p;
  }

  bool access::object_traits_impl< ::TR::Core::CustomQueryData, id_mysql >::
  find (database& db, const id_type& id, object_type& obj)
  {
    using namespace mysql;

    mysql::connection& conn (
      mysql::transaction::current ().connection ());
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    statements_type::auto_lock l (sts);

    if (!find_ (sts, &id))
      return false;

    select_statement& st (sts.find_statement ());
    ODB_POTENTIALLY_UNUSED (st);

    reference_cache_traits::position_type pos (
      reference_cache_traits::insert (db, id, obj));
    reference_cache_traits::insert_guard ig (pos);

    callback (db, obj, callback_event::pre_load);
    init (obj, sts.image (), &db);
    load_ (sts, obj, false);
    sts.load_delayed (0);
    l.unlock ();
    callback (db, obj, callback_event::post_load);
    reference_cache_traits::load (pos);
    ig.release ();
    return true;
  }

  bool access::object_traits_impl< ::TR::Core::CustomQueryData, id_mysql >::
  reload (database& db, object_type& obj)
  {
    using namespace mysql;

    mysql::connection& conn (
      mysql::transaction::current ().connection ());
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    statements_type::auto_lock l (sts);

    const id_type& id  (
      obj.m_key);

    if (!find_ (sts, &id))
      return false;

    select_statement& st (sts.find_statement ());
    ODB_POTENTIALLY_UNUSED (st);

    callback (db, obj, callback_event::pre_load);
    init (obj, sts.image (), &db);
    load_ (sts, obj, true);
    sts.load_delayed (0);
    l.unlock ();
    callback (db, obj, callback_event::post_load);
    return true;
  }

  bool access::object_traits_impl< ::TR::Core::CustomQueryData, id_mysql >::
  find_ (statements_type& sts,
         const id_type* id)
  {
    using namespace mysql;

    id_image_type& i (sts.id_image ());
    init (i, *id);

    binding& idb (sts.id_image_binding ());
    if (i.version != sts.id_image_version () || idb.version == 0)
    {
      bind (idb.bind, i);
      sts.id_image_version (i.version);
      idb.version++;
    }

    image_type& im (sts.image ());
    binding& imb (sts.select_image_binding ());

    if (im.version != sts.select_image_version () ||
        imb.version == 0)
    {
      bind (imb.bind, im, statement_select);
      sts.select_image_version (im.version);
      imb.version++;
    }

    select_statement& st (sts.find_statement ());

    st.execute ();
    auto_result ar (st);
    select_statement::result r (st.fetch ());

    if (r == select_statement::truncated)
    {
      if (grow (im, sts.select_image_truncated ()))
        im.version++;

      if (im.version != sts.select_image_version ())
      {
        bind (imb.bind, im, statement_select);
        sts.select_image_version (im.version);
        imb.version++;
        st.refetch ();
      }
    }

    return r != select_statement::no_data;
  }

  void access::object_traits_impl< ::TR::Core::CustomQueryData, id_mysql >::
  load_ (statements_type& sts,
         object_type& obj,
         bool reload)
  {
    ODB_POTENTIALLY_UNUSED (reload);

    extra_statement_cache_type& esc (sts.extra_statement_cache ());

    // m_input_uuids
    //
    {
      ::std::vector< ::TR::Core::ReportTypeUUID >& v =
        obj.m_input_uuids;

      input_uuids_traits::load (
        v,
        esc.m_input_uuids);
    }
  }

  result< access::object_traits_impl< ::TR::Core::CustomQueryData, id_mysql >::object_type >
  access::object_traits_impl< ::TR::Core::CustomQueryData, id_mysql >::
  query (database&, const query_base_type& q)
  {
    using namespace mysql;
    using odb::details::shared;
    using odb::details::shared_ptr;

    mysql::connection& conn (
      mysql::transaction::current ().connection ());

    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    image_type& im (sts.image ());
    binding& imb (sts.select_image_binding ());

    if (im.version != sts.select_image_version () ||
        imb.version == 0)
    {
      bind (imb.bind, im, statement_select);
      sts.select_image_version (im.version);
      imb.version++;
    }

    std::string text (query_statement);
    if (!q.empty ())
    {
      text += " ";
      text += q.clause ();
    }

    q.init_parameters ();
    shared_ptr<select_statement> st (
      new (shared) select_statement (
        conn,
        text,
        false,
        true,
        q.parameters_binding (),
        imb));

    st->execute ();

    shared_ptr< odb::object_result_impl<object_type> > r (
      new (shared) mysql::object_result_impl<object_type> (
        q, st, sts, 0));

    return result<object_type> (r);
  }

  unsigned long long access::object_traits_impl< ::TR::Core::CustomQueryData, id_mysql >::
  erase_query (database&, const query_base_type& q)
  {
    using namespace mysql;

    mysql::connection& conn (
      mysql::transaction::current ().connection ());

    std::string text (erase_query_statement);
    if (!q.empty ())
    {
      text += ' ';
      text += q.clause ();
    }

    q.init_parameters ();
    delete_statement st (
      conn,
      text,
      q.parameters_binding ());

    return st.execute ();
  }
}

namespace odb
{
  static bool
  create_schema (database& db, unsigned short pass, bool drop)
  {
    ODB_POTENTIALLY_UNUSED (db);
    ODB_POTENTIALLY_UNUSED (pass);
    ODB_POTENTIALLY_UNUSED (drop);

    if (drop)
    {
      switch (pass)
      {
        case 1:
        {
          return true;
        }
        case 2:
        {
          db.execute ("DROP TABLE IF EXISTS `CustomQueryData_input_uuids`");
          db.execute ("DROP TABLE IF EXISTS `CustomQueryData`");
          return false;
        }
      }
    }
    else
    {
      switch (pass)
      {
        case 1:
        {
          db.execute ("CREATE TABLE `CustomQueryData` (\n"
                      "  `key` INT NOT NULL PRIMARY KEY AUTO_INCREMENT,\n"
                      "  `name` TEXT NOT NULL,\n"
                      "  `query_doc_value` TEXT NOT NULL,\n"
                      "  `query_def_value` TEXT NOT NULL,\n"
                      "  `output_uuid_value` BINARY(16) NULL,\n"
                      "  `output_def_value` TEXT NOT NULL,\n"
                      "  `output_traits` INT NOT NULL)\n"
                      " ENGINE=InnoDB");
          db.execute ("CREATE TABLE `CustomQueryData_input_uuids` (\n"
                      "  `object_id` INT NOT NULL,\n"
                      "  `index` BIGINT UNSIGNED NOT NULL,\n"
                      "  `value_value` BINARY(16) NULL,\n"
                      "  CONSTRAINT `CustomQueryData_input_uuids_object_id_fk`\n"
                      "    FOREIGN KEY (`object_id`)\n"
                      "    REFERENCES `CustomQueryData` (`key`)\n"
                      "    ON DELETE CASCADE)\n"
                      " ENGINE=InnoDB");
          db.execute ("CREATE INDEX `object_id_i`\n"
                      "  ON `CustomQueryData_input_uuids` (`object_id`)");
          db.execute ("CREATE INDEX `index_i`\n"
                      "  ON `CustomQueryData_input_uuids` (`index`)");
          return false;
        }
      }
    }

    return false;
  }

  static const schema_catalog_create_entry
  create_schema_entry_ (
    id_mysql,
    "",
    &create_schema);
}

#include <odb/post.hxx>
