// This file was generated by ODB, object-relational mapping (ORM)
// compiler for C++.
//

#ifndef REPORT_POLICY_DATA_ODB_HXX
#define REPORT_POLICY_DATA_ODB_HXX

// Begin prologue.
//
#include <odb/boost/version.hxx>
#if ODB_BOOST_VERSION != 2040000 // 2.4.0
#  error ODB and C++ compilers see different libodb-boost interface versions
#endif
#include <boost/shared_ptr.hpp>
#include <odb/boost/smart-ptr/pointer-traits.hxx>
#include <odb/boost/smart-ptr/wrapper-traits.hxx>
#include <odb/boost/optional/wrapper-traits.hxx>
#include <odb/boost/unordered/container-traits.hxx>
#include <odb/boost/date-time/mysql/gregorian-traits.hxx>
#include <odb/boost/date-time/mysql/posix-time-traits.hxx>
#include <odb/boost/multi-index/container-traits.hxx>
#include <odb/boost/uuid/mysql/uuid-traits.hxx>
//
// End prologue.

#include <odb/version.hxx>

#if (ODB_VERSION != 20400UL)
#error ODB runtime version mismatch
#endif

#include <odb/pre.hxx>

#include "ReportPolicyData.hxx"

#include "BasisValues-odb.hxx"
#include "RegistryValues-odb.hxx"
#include "Values-odb.hxx"

#include <memory>
#include <cstddef>
#include <utility>

#include <odb/core.hxx>
#include <odb/traits.hxx>
#include <odb/callback.hxx>
#include <odb/wrapper-traits.hxx>
#include <odb/pointer-traits.hxx>
#ifdef BOOST_TR1_MEMORY_HPP_INCLUDED
#  include <odb/tr1/wrapper-traits.hxx>
#  include <odb/tr1/pointer-traits.hxx>
#endif
#include <odb/container-traits.hxx>
#include <odb/no-op-cache-traits.hxx>
#include <odb/result.hxx>
#include <odb/simple-object-result.hxx>

#include <odb/details/unused.hxx>
#include <odb/details/shared-ptr.hxx>

namespace odb
{
  // ResourcePolicyData
  //
  template <>
  struct class_traits< ::TR::Core::ResourcePolicyData >
  {
    static const class_kind kind = class_object;
  };

  template <>
  class access::object_traits< ::TR::Core::ResourcePolicyData >
  {
    public:
    typedef ::TR::Core::ResourcePolicyData object_type;
    typedef ::boost::shared_ptr< ::TR::Core::ResourcePolicyData > pointer_type;
    typedef odb::pointer_traits<pointer_type> pointer_traits;

    static const bool polymorphic = false;

    typedef ::TR::Core::ResourcePolicyIdentity id_type;

    static const bool auto_id = false;

    static const bool abstract = false;

    static id_type
    id (const object_type&);

    typedef
    no_op_pointer_cache_traits<pointer_type>
    pointer_cache_traits;

    typedef
    no_op_reference_cache_traits<object_type>
    reference_cache_traits;

    static void
    callback (database&, object_type&, callback_event);

    static void
    callback (database&, const object_type&, callback_event);
  };
}

#include <odb/details/buffer.hxx>

#include <odb/mysql/version.hxx>
#include <odb/mysql/forward.hxx>
#include <odb/mysql/binding.hxx>
#include <odb/mysql/mysql-types.hxx>
#include <odb/mysql/query.hxx>

namespace odb
{
  // ResourcePolicyIdentity
  //
  template <>
  class access::composite_value_traits< ::TR::Core::ResourcePolicyIdentity, id_mysql >
  {
    public:
    typedef ::TR::Core::ResourcePolicyIdentity value_type;

    struct image_type
    {
      // m_subject
      //
      composite_value_traits< ::TR::Core::SubjectIdentity, id_mysql >::image_type m_subject_value;

      // m_resource
      //
      composite_value_traits< ::TR::Core::ResourceIdentity, id_mysql >::image_type m_resource_value;
    };

    static bool
    grow (image_type&,
          my_bool*);

    static void
    bind (MYSQL_BIND*,
          image_type&,
          mysql::statement_kind);

    static bool
    init (image_type&,
          const value_type&,
          mysql::statement_kind);

    static void
    init (value_type&,
          const image_type&,
          database*);

    static bool
    get_null (const image_type&);

    static void
    set_null (image_type&,
              mysql::statement_kind);

    static const std::size_t column_count = 4UL;
  };

  // ResourcePolicyData
  //
  template <typename A>
  struct query_columns< ::TR::Core::ResourcePolicyData, id_mysql, A >
  {
    // identity
    //
    struct identity_class_
    {
      identity_class_ ()
      {
      }

      // subject
      //
      struct subject_class_1_
      {
        subject_class_1_ ()
        {
        }

        // value1
        //
        struct value1_class_2_
        {
          value1_class_2_ ()
          {
          }

          // value
          //
          typedef
          mysql::query_column<
            mysql::value_traits<
              int,
              mysql::id_long >::query_type,
            mysql::id_long >
          value_type_;

          static const value_type_ value;
        };

        static const value1_class_2_ value1;

        // value2
        //
        struct value2_class_2_
        {
          value2_class_2_ ()
          {
          }

          // value
          //
          typedef
          mysql::query_column<
            mysql::value_traits<
              int,
              mysql::id_long >::query_type,
            mysql::id_long >
          value_type_;

          static const value_type_ value;
        };

        static const value2_class_2_ value2;
      };

      static const subject_class_1_ subject;

      // resource
      //
      struct resource_class_1_
      {
        resource_class_1_ ()
        {
        }

        // value1
        //
        struct value1_class_2_
        {
          value1_class_2_ ()
          {
          }

          // value
          //
          typedef
          mysql::query_column<
            mysql::value_traits<
              ::boost::uuids::uuid,
              mysql::id_blob >::query_type,
            mysql::id_blob >
          value_type_;

          static const value_type_ value;
        };

        static const value1_class_2_ value1;

        // value2
        //
        struct value2_class_2_
        {
          value2_class_2_ ()
          {
          }

          // value
          //
          typedef
          mysql::query_column<
            mysql::value_traits<
              ::boost::uuids::uuid,
              mysql::id_blob >::query_type,
            mysql::id_blob >
          value_type_;

          static const value_type_ value;
        };

        static const value2_class_2_ value2;
      };

      static const resource_class_1_ resource;
    };

    static const identity_class_ identity;

    // enable_policy
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        ::TR::Core::EnablePolicy,
        mysql::id_long >::query_type,
      mysql::id_long >
    enable_policy_type_;

    static const enable_policy_type_ enable_policy;

    // visibility
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        ::TR::Core::Visibility,
        mysql::id_long >::query_type,
      mysql::id_long >
    visibility_type_;

    static const visibility_type_ visibility;

    // defer_policy
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        ::TR::Core::DeferPolicy,
        mysql::id_long >::query_type,
      mysql::id_long >
    defer_policy_type_;

    static const defer_policy_type_ defer_policy;

    // setup_uuid
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        ::TR::Core::UUID,
        mysql::id_blob >::query_type,
      mysql::id_blob >
    setup_uuid_type_;

    static const setup_uuid_type_ setup_uuid;
  };

  template <typename A>
  const typename query_columns< ::TR::Core::ResourcePolicyData, id_mysql, A >::identity_class_::subject_class_1_::value1_class_2_::value_type_
  query_columns< ::TR::Core::ResourcePolicyData, id_mysql, A >::identity_class_::subject_class_1_::value1_class_2_::
  value (A::table_name, "`identity_subject_value1_value`", 0);

  template <typename A>
  const typename query_columns< ::TR::Core::ResourcePolicyData, id_mysql, A >::identity_class_::subject_class_1_::value1_class_2_
  query_columns< ::TR::Core::ResourcePolicyData, id_mysql, A >::identity_class_::subject_class_1_::value1;

  template <typename A>
  const typename query_columns< ::TR::Core::ResourcePolicyData, id_mysql, A >::identity_class_::subject_class_1_::value2_class_2_::value_type_
  query_columns< ::TR::Core::ResourcePolicyData, id_mysql, A >::identity_class_::subject_class_1_::value2_class_2_::
  value (A::table_name, "`identity_subject_value2_value`", 0);

  template <typename A>
  const typename query_columns< ::TR::Core::ResourcePolicyData, id_mysql, A >::identity_class_::subject_class_1_::value2_class_2_
  query_columns< ::TR::Core::ResourcePolicyData, id_mysql, A >::identity_class_::subject_class_1_::value2;

  template <typename A>
  const typename query_columns< ::TR::Core::ResourcePolicyData, id_mysql, A >::identity_class_::subject_class_1_
  query_columns< ::TR::Core::ResourcePolicyData, id_mysql, A >::identity_class_::subject;

  template <typename A>
  const typename query_columns< ::TR::Core::ResourcePolicyData, id_mysql, A >::identity_class_::resource_class_1_::value1_class_2_::value_type_
  query_columns< ::TR::Core::ResourcePolicyData, id_mysql, A >::identity_class_::resource_class_1_::value1_class_2_::
  value (A::table_name, "`identity_resource_value1_value`", 0);

  template <typename A>
  const typename query_columns< ::TR::Core::ResourcePolicyData, id_mysql, A >::identity_class_::resource_class_1_::value1_class_2_
  query_columns< ::TR::Core::ResourcePolicyData, id_mysql, A >::identity_class_::resource_class_1_::value1;

  template <typename A>
  const typename query_columns< ::TR::Core::ResourcePolicyData, id_mysql, A >::identity_class_::resource_class_1_::value2_class_2_::value_type_
  query_columns< ::TR::Core::ResourcePolicyData, id_mysql, A >::identity_class_::resource_class_1_::value2_class_2_::
  value (A::table_name, "`identity_resource_value2_value`", 0);

  template <typename A>
  const typename query_columns< ::TR::Core::ResourcePolicyData, id_mysql, A >::identity_class_::resource_class_1_::value2_class_2_
  query_columns< ::TR::Core::ResourcePolicyData, id_mysql, A >::identity_class_::resource_class_1_::value2;

  template <typename A>
  const typename query_columns< ::TR::Core::ResourcePolicyData, id_mysql, A >::identity_class_::resource_class_1_
  query_columns< ::TR::Core::ResourcePolicyData, id_mysql, A >::identity_class_::resource;

  template <typename A>
  const typename query_columns< ::TR::Core::ResourcePolicyData, id_mysql, A >::identity_class_
  query_columns< ::TR::Core::ResourcePolicyData, id_mysql, A >::identity;

  template <typename A>
  const typename query_columns< ::TR::Core::ResourcePolicyData, id_mysql, A >::enable_policy_type_
  query_columns< ::TR::Core::ResourcePolicyData, id_mysql, A >::
  enable_policy (A::table_name, "`enable_policy`", 0);

  template <typename A>
  const typename query_columns< ::TR::Core::ResourcePolicyData, id_mysql, A >::visibility_type_
  query_columns< ::TR::Core::ResourcePolicyData, id_mysql, A >::
  visibility (A::table_name, "`visibility`", 0);

  template <typename A>
  const typename query_columns< ::TR::Core::ResourcePolicyData, id_mysql, A >::defer_policy_type_
  query_columns< ::TR::Core::ResourcePolicyData, id_mysql, A >::
  defer_policy (A::table_name, "`defer_policy`", 0);

  template <typename A>
  const typename query_columns< ::TR::Core::ResourcePolicyData, id_mysql, A >::setup_uuid_type_
  query_columns< ::TR::Core::ResourcePolicyData, id_mysql, A >::
  setup_uuid (A::table_name, "`setup_uuid`", 0);

  template <typename A>
  struct pointer_query_columns< ::TR::Core::ResourcePolicyData, id_mysql, A >:
    query_columns< ::TR::Core::ResourcePolicyData, id_mysql, A >
  {
  };

  template <>
  class access::object_traits_impl< ::TR::Core::ResourcePolicyData, id_mysql >:
    public access::object_traits< ::TR::Core::ResourcePolicyData >
  {
    public:
    struct id_image_type
    {
      composite_value_traits< ::TR::Core::ResourcePolicyIdentity, id_mysql >::image_type id_value;

      std::size_t version;
    };

    struct image_type
    {
      // m_identity
      //
      composite_value_traits< ::TR::Core::ResourcePolicyIdentity, id_mysql >::image_type m_identity_value;

      // m_enable_policy
      //
      int m_enable_policy_value;
      my_bool m_enable_policy_null;

      // m_visibility
      //
      int m_visibility_value;
      my_bool m_visibility_null;

      // m_defer_policy
      //
      int m_defer_policy_value;
      my_bool m_defer_policy_null;

      // m_setup_uuid
      //
      details::buffer m_setup_uuid_value;
      unsigned long m_setup_uuid_size;
      my_bool m_setup_uuid_null;

      std::size_t version;
    };

    struct extra_statement_cache_type;

    using object_traits<object_type>::id;

    static id_type
    id (const image_type&);

    static bool
    grow (image_type&,
          my_bool*);

    static void
    bind (MYSQL_BIND*,
          image_type&,
          mysql::statement_kind);

    static void
    bind (MYSQL_BIND*, id_image_type&);

    static bool
    init (image_type&,
          const object_type&,
          mysql::statement_kind);

    static void
    init (object_type&,
          const image_type&,
          database*);

    static void
    init (id_image_type&, const id_type&);

    typedef mysql::object_statements<object_type> statements_type;

    typedef mysql::query_base query_base_type;

    static const std::size_t column_count = 8UL;
    static const std::size_t id_column_count = 4UL;
    static const std::size_t inverse_column_count = 0UL;
    static const std::size_t readonly_column_count = 0UL;
    static const std::size_t managed_optimistic_column_count = 0UL;

    static const std::size_t separate_load_column_count = 0UL;
    static const std::size_t separate_update_column_count = 0UL;

    static const bool versioned = false;

    static const char persist_statement[];
    static const char find_statement[];
    static const char update_statement[];
    static const char erase_statement[];
    static const char query_statement[];
    static const char erase_query_statement[];

    static const char table_name[];

    static void
    persist (database&, const object_type&);

    static pointer_type
    find (database&, const id_type&);

    static bool
    find (database&, const id_type&, object_type&);

    static bool
    reload (database&, object_type&);

    static void
    update (database&, const object_type&);

    static void
    erase (database&, const id_type&);

    static void
    erase (database&, const object_type&);

    static result<object_type>
    query (database&, const query_base_type&);

    static unsigned long long
    erase_query (database&, const query_base_type&);

    public:
    static bool
    find_ (statements_type&,
           const id_type*);

    static void
    load_ (statements_type&,
           object_type&,
           bool reload);
  };

  template <>
  class access::object_traits_impl< ::TR::Core::ResourcePolicyData, id_common >:
    public access::object_traits_impl< ::TR::Core::ResourcePolicyData, id_mysql >
  {
  };

  // ResourcePolicyData
  //
}

#include "ReportPolicyData-odb.ixx"

#include <odb/post.hxx>

#endif // REPORT_POLICY_DATA_ODB_HXX
