// This file was generated by ODB, object-relational mapping (ORM)
// compiler for C++.
//

#ifndef STREAM_INPUT_DATA_ODB_HXX
#define STREAM_INPUT_DATA_ODB_HXX

// Begin prologue.
//
#include <odb/boost/version.hxx>
#if ODB_BOOST_VERSION != 2040000 // 2.4.0
#  error ODB and C++ compilers see different libodb-boost interface versions
#endif
#include <boost/shared_ptr.hpp>
#include <odb/boost/smart-ptr/pointer-traits.hxx>
#include <odb/boost/smart-ptr/wrapper-traits.hxx>
#include <odb/boost/optional/wrapper-traits.hxx>
#include <odb/boost/unordered/container-traits.hxx>
#include <odb/boost/date-time/mysql/gregorian-traits.hxx>
#include <odb/boost/date-time/mysql/posix-time-traits.hxx>
#include <odb/boost/multi-index/container-traits.hxx>
#include <odb/boost/uuid/mysql/uuid-traits.hxx>
//
// End prologue.

#include <odb/version.hxx>

#if (ODB_VERSION != 20400UL)
#error ODB runtime version mismatch
#endif

#include <odb/pre.hxx>

#include "StreamInputData.hxx"

#include "BasisValues-odb.hxx"
#include "RegistryValues-odb.hxx"
#include "Values-odb.hxx"

#include <memory>
#include <cstddef>
#include <utility>

#include <odb/core.hxx>
#include <odb/traits.hxx>
#include <odb/callback.hxx>
#include <odb/wrapper-traits.hxx>
#include <odb/pointer-traits.hxx>
#ifdef BOOST_TR1_MEMORY_HPP_INCLUDED
#  include <odb/tr1/wrapper-traits.hxx>
#  include <odb/tr1/pointer-traits.hxx>
#endif
#include <odb/container-traits.hxx>
#include <odb/no-op-cache-traits.hxx>
#include <odb/result.hxx>
#include <odb/simple-object-result.hxx>

#include <odb/details/unused.hxx>
#include <odb/details/shared-ptr.hxx>

namespace odb
{
  // StreamInputData
  //
  template <>
  struct class_traits< ::TR::Core::StreamInputData >
  {
    static const class_kind kind = class_object;
  };

  template <>
  class access::object_traits< ::TR::Core::StreamInputData >
  {
    public:
    typedef ::TR::Core::StreamInputData object_type;
    typedef ::boost::shared_ptr< ::TR::Core::StreamInputData > pointer_type;
    typedef odb::pointer_traits<pointer_type> pointer_traits;

    static const bool polymorphic = false;

    typedef int id_type;

    static const bool auto_id = true;

    static const bool abstract = false;

    static id_type
    id (const object_type&);

    typedef
    no_op_pointer_cache_traits<pointer_type>
    pointer_cache_traits;

    typedef
    no_op_reference_cache_traits<object_type>
    reference_cache_traits;

    static void
    callback (database&, object_type&, callback_event);

    static void
    callback (database&, const object_type&, callback_event);
  };
}

#include <odb/details/buffer.hxx>

#include <odb/mysql/version.hxx>
#include <odb/mysql/forward.hxx>
#include <odb/mysql/binding.hxx>
#include <odb/mysql/mysql-types.hxx>
#include <odb/mysql/query.hxx>

namespace odb
{
  // StreamRecordData
  //
  template <>
  class access::composite_value_traits< ::TR::Core::StreamRecordData, id_mysql >
  {
    public:
    typedef ::TR::Core::StreamRecordData value_type;

    struct image_type
    {
      // m_key
      //
      int m_key_value;
      my_bool m_key_null;

      // m_source_key
      //
      composite_value_traits< ::TR::Core::SourceKey, id_mysql >::image_type m_source_key_value;

      // m_stream_type_uuid
      //
      composite_value_traits< ::TR::Core::StreamTypeUUID, id_mysql >::image_type m_stream_type_uuid_value;

      // m_message
      //
      details::buffer m_message_value;
      unsigned long m_message_size;
      my_bool m_message_null;

      // m_time
      //
      long long m_time_value;
      my_bool m_time_null;
    };

    static bool
    grow (image_type&,
          my_bool*);

    static void
    bind (MYSQL_BIND*,
          image_type&,
          mysql::statement_kind);

    static bool
    init (image_type&,
          const value_type&,
          mysql::statement_kind);

    static void
    init (value_type&,
          const image_type&,
          database*);

    static bool
    get_null (const image_type&);

    static void
    set_null (image_type&,
              mysql::statement_kind);

    static const std::size_t column_count = 5UL;
  };

  // StreamInputData
  //
  template <typename A>
  struct query_columns< ::TR::Core::StreamInputData, id_mysql, A >
  {
    // key
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        int,
        mysql::id_long >::query_type,
      mysql::id_long >
    key_type_;

    static const key_type_ key;

    // source_key
    //
    struct source_key_class_
    {
      source_key_class_ ()
      {
      }

      // value
      //
      typedef
      mysql::query_column<
        mysql::value_traits<
          int,
          mysql::id_long >::query_type,
        mysql::id_long >
      value_type_;

      static const value_type_ value;
    };

    static const source_key_class_ source_key;

    // stream_type_uuid
    //
    struct stream_type_uuid_class_
    {
      stream_type_uuid_class_ ()
      {
      }

      // value
      //
      typedef
      mysql::query_column<
        mysql::value_traits<
          ::boost::uuids::uuid,
          mysql::id_blob >::query_type,
        mysql::id_blob >
      value_type_;

      static const value_type_ value;
    };

    static const stream_type_uuid_class_ stream_type_uuid;

    // input_record
    //
    struct input_record_class_
    {
      input_record_class_ ()
      {
      }

      // key
      //
      typedef
      mysql::query_column<
        mysql::value_traits<
          int,
          mysql::id_long >::query_type,
        mysql::id_long >
      key_type_;

      static const key_type_ key;

      // source_key
      //
      struct source_key_class_1_
      {
        source_key_class_1_ ()
        {
        }

        // value
        //
        typedef
        mysql::query_column<
          mysql::value_traits<
            int,
            mysql::id_long >::query_type,
          mysql::id_long >
        value_type_;

        static const value_type_ value;
      };

      static const source_key_class_1_ source_key;

      // stream_type_uuid
      //
      struct stream_type_uuid_class_1_
      {
        stream_type_uuid_class_1_ ()
        {
        }

        // value
        //
        typedef
        mysql::query_column<
          mysql::value_traits<
            ::boost::uuids::uuid,
            mysql::id_blob >::query_type,
          mysql::id_blob >
        value_type_;

        static const value_type_ value;
      };

      static const stream_type_uuid_class_1_ stream_type_uuid;

      // message
      //
      typedef
      mysql::query_column<
        mysql::value_traits<
          ::std::string,
          mysql::id_string >::query_type,
        mysql::id_string >
      message_type_;

      static const message_type_ message;

      // time
      //
      typedef
      mysql::query_column<
        mysql::value_traits<
          ::time_t,
          mysql::id_longlong >::query_type,
        mysql::id_longlong >
      time_type_;

      static const time_type_ time;
    };

    static const input_record_class_ input_record;
  };

  template <typename A>
  const typename query_columns< ::TR::Core::StreamInputData, id_mysql, A >::key_type_
  query_columns< ::TR::Core::StreamInputData, id_mysql, A >::
  key (A::table_name, "`key`", 0);

  template <typename A>
  const typename query_columns< ::TR::Core::StreamInputData, id_mysql, A >::source_key_class_::value_type_
  query_columns< ::TR::Core::StreamInputData, id_mysql, A >::source_key_class_::
  value (A::table_name, "`source_key_value`", 0);

  template <typename A>
  const typename query_columns< ::TR::Core::StreamInputData, id_mysql, A >::source_key_class_
  query_columns< ::TR::Core::StreamInputData, id_mysql, A >::source_key;

  template <typename A>
  const typename query_columns< ::TR::Core::StreamInputData, id_mysql, A >::stream_type_uuid_class_::value_type_
  query_columns< ::TR::Core::StreamInputData, id_mysql, A >::stream_type_uuid_class_::
  value (A::table_name, "`stream_type_uuid_value`", 0);

  template <typename A>
  const typename query_columns< ::TR::Core::StreamInputData, id_mysql, A >::stream_type_uuid_class_
  query_columns< ::TR::Core::StreamInputData, id_mysql, A >::stream_type_uuid;

  template <typename A>
  const typename query_columns< ::TR::Core::StreamInputData, id_mysql, A >::input_record_class_::key_type_
  query_columns< ::TR::Core::StreamInputData, id_mysql, A >::input_record_class_::
  key (A::table_name, "`input_record_key`", 0);

  template <typename A>
  const typename query_columns< ::TR::Core::StreamInputData, id_mysql, A >::input_record_class_::source_key_class_1_::value_type_
  query_columns< ::TR::Core::StreamInputData, id_mysql, A >::input_record_class_::source_key_class_1_::
  value (A::table_name, "`input_record_source_key_value`", 0);

  template <typename A>
  const typename query_columns< ::TR::Core::StreamInputData, id_mysql, A >::input_record_class_::source_key_class_1_
  query_columns< ::TR::Core::StreamInputData, id_mysql, A >::input_record_class_::source_key;

  template <typename A>
  const typename query_columns< ::TR::Core::StreamInputData, id_mysql, A >::input_record_class_::stream_type_uuid_class_1_::value_type_
  query_columns< ::TR::Core::StreamInputData, id_mysql, A >::input_record_class_::stream_type_uuid_class_1_::
  value (A::table_name, "`input_record_stream_type_uuid_value`", 0);

  template <typename A>
  const typename query_columns< ::TR::Core::StreamInputData, id_mysql, A >::input_record_class_::stream_type_uuid_class_1_
  query_columns< ::TR::Core::StreamInputData, id_mysql, A >::input_record_class_::stream_type_uuid;

  template <typename A>
  const typename query_columns< ::TR::Core::StreamInputData, id_mysql, A >::input_record_class_::message_type_
  query_columns< ::TR::Core::StreamInputData, id_mysql, A >::input_record_class_::
  message (A::table_name, "`input_record_message`", 0);

  template <typename A>
  const typename query_columns< ::TR::Core::StreamInputData, id_mysql, A >::input_record_class_::time_type_
  query_columns< ::TR::Core::StreamInputData, id_mysql, A >::input_record_class_::
  time (A::table_name, "`input_record_time`", 0);

  template <typename A>
  const typename query_columns< ::TR::Core::StreamInputData, id_mysql, A >::input_record_class_
  query_columns< ::TR::Core::StreamInputData, id_mysql, A >::input_record;

  template <typename A>
  struct pointer_query_columns< ::TR::Core::StreamInputData, id_mysql, A >:
    query_columns< ::TR::Core::StreamInputData, id_mysql, A >
  {
  };

  template <>
  class access::object_traits_impl< ::TR::Core::StreamInputData, id_mysql >:
    public access::object_traits< ::TR::Core::StreamInputData >
  {
    public:
    struct id_image_type
    {
      int id_value;
      my_bool id_null;

      std::size_t version;
    };

    struct image_type
    {
      // m_key
      //
      int m_key_value;
      my_bool m_key_null;

      // m_source_key
      //
      composite_value_traits< ::TR::Core::SourceKey, id_mysql >::image_type m_source_key_value;

      // m_stream_type_uuid
      //
      composite_value_traits< ::TR::Core::StreamTypeUUID, id_mysql >::image_type m_stream_type_uuid_value;

      // m_input_record
      //
      composite_value_traits< ::TR::Core::StreamRecordData, id_mysql >::image_type m_input_record_value;

      std::size_t version;
    };

    struct extra_statement_cache_type;

    using object_traits<object_type>::id;

    static id_type
    id (const id_image_type&);

    static id_type
    id (const image_type&);

    static bool
    grow (image_type&,
          my_bool*);

    static void
    bind (MYSQL_BIND*,
          image_type&,
          mysql::statement_kind);

    static void
    bind (MYSQL_BIND*, id_image_type&);

    static bool
    init (image_type&,
          const object_type&,
          mysql::statement_kind);

    static void
    init (object_type&,
          const image_type&,
          database*);

    static void
    init (id_image_type&, const id_type&);

    typedef mysql::object_statements<object_type> statements_type;

    typedef mysql::query_base query_base_type;

    static const std::size_t column_count = 8UL;
    static const std::size_t id_column_count = 1UL;
    static const std::size_t inverse_column_count = 0UL;
    static const std::size_t readonly_column_count = 0UL;
    static const std::size_t managed_optimistic_column_count = 0UL;

    static const std::size_t separate_load_column_count = 0UL;
    static const std::size_t separate_update_column_count = 0UL;

    static const bool versioned = false;

    static const char persist_statement[];
    static const char find_statement[];
    static const char update_statement[];
    static const char erase_statement[];
    static const char query_statement[];
    static const char erase_query_statement[];

    static const char table_name[];

    static void
    persist (database&, object_type&);

    static pointer_type
    find (database&, const id_type&);

    static bool
    find (database&, const id_type&, object_type&);

    static bool
    reload (database&, object_type&);

    static void
    update (database&, const object_type&);

    static void
    erase (database&, const id_type&);

    static void
    erase (database&, const object_type&);

    static result<object_type>
    query (database&, const query_base_type&);

    static unsigned long long
    erase_query (database&, const query_base_type&);

    public:
    static bool
    find_ (statements_type&,
           const id_type*);

    static void
    load_ (statements_type&,
           object_type&,
           bool reload);
  };

  template <>
  class access::object_traits_impl< ::TR::Core::StreamInputData, id_common >:
    public access::object_traits_impl< ::TR::Core::StreamInputData, id_mysql >
  {
  };

  // StreamInputData
  //
}

#include "StreamInputData-odb.ixx"

#include <odb/post.hxx>

#endif // STREAM_INPUT_DATA_ODB_HXX
